from __future__ import annotations

import contextlib
import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path

import pytest

from wall_in_one import config, deployed_upgrade, file_io, paths
from wall_in_one.library import (
    displays,
    favourites,
    pairing,
    pairings,
    playlists,
    removals,
    schedules,
)
from wall_in_one.library import model as library_model


@dataclass(frozen=True, slots=True)
class _Profile:
    root: Path
    automatic: Path
    entries: tuple[tuple[Path, Path], ...]
    marker: Path


def _old_settings(*, active_playlist: str = "") -> str:
    return f'''# wall-in-one settings
# empty follows Noctalia's own wallpaper directory
roots = []
opacity = 1.00
preview_scheme = "m3-tonal-spot"
follow_noctalia_palette = true
cycle_interval = 300
cycle_enabled = false
shuffle = false
dynamics_enabled = true
video_muted = true
video_volume = 100
video_when_hidden = "pause"
cycle_favourites_only = false
active_playlist = "{active_playlist}"
scan_workshop = true
own_scene_renderer = true
output = ""
'''


def _entry_id(source: Path) -> str:
    return hashlib.sha256(os.fsencode(source)).hexdigest()[:16]


def _runtime(
    entries: tuple[tuple[Path, Path], ...],
    *,
    named: tuple[tuple[str, str, tuple[tuple[str, Path, Path], ...]], ...] = (),
    default: str = "all-media",
    extra_top_level: str = "",
) -> str:
    lines = [
        "# Generated by Wall-in-One. Edit the library in the app, not this file.",
        "schema_version = 2",
        f'default_playlist = "{default}"',
        extra_top_level,
        "",
        "[settings]",
        "cycle_interval_seconds = 300",
        "cycle_enabled = false",
        "shuffle = false",
        "dynamics_enabled = true",
        "",
        "[renderer]",
        'noctalia_program = "/usr/bin/noctalia"',
        'niri_program = "/usr/bin/niri"',
        'mpvpaper_program = "/usr/bin/mpvpaper"',
        'linux_wallpaperengine_program = "/usr/bin/linux-wallpaperengine"',
        "own_scene_renderer = true",
        'layer = "background"',
        'video_when_hidden = "pause"',
        "video_hardware_decode = true",
        "video_muted = true",
        "video_volume = 100",
        "scene_fps = 30",
        "scene_muted = true",
        "scene_volume = 100",
        "scene_pause_when_covered = true",
        'scene_scaling = ""',
        'scene_clamp = ""',
        "",
        "[[playlists]]",
        'id = "all-media"',
        'name = "All media"',
    ]
    for source, capture in entries:
        lines.extend(
            (
                "",
                "[[playlists.entries]]",
                f'id = "{_entry_id(source)}"',
                'kind = "video"',
                f"still = {json.dumps(str(capture))}",
                f"motion = {json.dumps(str(source))}",
                'palette = { kind = "keep", mode = "keep" }',
            )
        )
    for identifier, name, authored_entries in named:
        lines.extend(("", "[[playlists]]", f'id = "{identifier}"', f'name = "{name}"'))
        for entry_id, source, capture in authored_entries:
            lines.extend(
                (
                    "",
                    "[[playlists.entries]]",
                    f'id = "{entry_id}"',
                    'kind = "video"',
                    f"still = {json.dumps(str(capture))}",
                    f"motion = {json.dumps(str(source))}",
                    'palette = { kind = "keep", mode = "keep" }',
                )
            )
    return "\n".join(line for line in lines if line != extra_top_level or line) + "\n"


def _profile(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    videos: int = 1,
    named_playlist: bool = False,
) -> _Profile:
    home = tmp_path / "home"
    config_home = tmp_path / "config"
    state_home = tmp_path / "state"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(config_home))
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    root = home / "wallpapers"
    automatic = root / "Wall-in-One" / "Automatic Stills"
    automatic.mkdir(parents=True)
    entries: list[tuple[Path, Path]] = []
    for ordinal in range(videos):
        source = root / f"clip-{ordinal}.mp4"
        capture = automatic / f"clip-{ordinal}.png"
        source.write_bytes(f"video-{ordinal}".encode())
        capture.write_bytes(b"\x89PNG\r\n\x1a\n" + bytes([ordinal]))
        entries.append((source, capture))
    marker = {
        "schema": 1,
        "plugin": "goober/wall-in-one",
        "kind": "automatic-stills",
        "ownership": "managed",
    }
    marker_path = automatic / ".managed-by-wall-in-one-v1.json"
    marker_path.write_text(json.dumps(marker) + "\n", encoding="utf-8")

    paths.settings_path().parent.mkdir(parents=True)
    active = "saved" if named_playlist else ""
    paths.settings_path().write_text(_old_settings(active_playlist=active), encoding="utf-8")
    paths.noctalia_settings_path().parent.mkdir(parents=True)
    paths.noctalia_settings_path().write_text(
        "[unrelated]\n"
        'directory = "/must/not/be-used"\n\n'
        "[wallpaper]\n"
        f"directory = {json.dumps(str(root))}\n",
        encoding="utf-8",
    )

    named: tuple[tuple[str, str, tuple[tuple[str, Path, Path], ...]], ...] = ()
    if named_playlist:
        source, capture = entries[0]
        saved = playlists.Playlist(
            id="saved",
            name="Saved",
            entries=(playlists.Entry(id="entry-a", source=str(source)),),
        )
        playlists.save({saved.id: saved})
        named = (("saved", "Saved", (("entry-a", source, capture),)),)
    paths.runtime_config_path().parent.mkdir(parents=True, exist_ok=True)
    paths.runtime_config_path().write_text(
        _runtime(tuple(entries), named=named, default=active or "all-media"),
        encoding="utf-8",
    )
    return _Profile(root, automatic, tuple(entries), marker_path)


def test_probe_distinguishes_absent_and_current_empty_root(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "config"))
    monkeypatch.setenv("XDG_STATE_HOME", str(tmp_path / "state"))
    assert deployed_upgrade.probe().status == "absent"
    config.save(config.Settings())
    assert deployed_upgrade.probe().status == "current"


def test_exact_profile_builds_generation_bound_read_only_plan(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch, videos=2, named_playlist=True)
    before = {
        path: path.read_bytes()
        for path in (
            paths.settings_path(),
            paths.runtime_config_path(),
            paths.noctalia_settings_path(),
            profile.marker,
        )
    }
    found = deployed_upgrade.probe()
    plan = deployed_upgrade.build_plan()
    assert found.status == "ready"
    assert found.counts == deployed_upgrade.UpgradeCounts(
        videos=2,
        captures=2,
        all_media_entries=2,
        playlists=1,
        playlist_entries=1,
        schedules=0,
    )
    assert plan.root == profile.root
    assert plan.automatic_stills == profile.automatic
    assert tuple(evidence.kind for evidence in plan.authoring_evidence) == (
        "pairings",
        "playlists",
        "schedules",
        "displays",
        "favourites",
        "pending-removals",
    )
    present_evidence = [evidence for evidence in plan.authoring_evidence if evidence.present]
    assert len(present_evidence) == 1
    assert present_evidence[0].kind == "playlists"
    assert present_evidence[0].fingerprint == file_io.file_fingerprint(
        playlists.state_path().lstat()
    )
    assert (
        present_evidence[0].sha256
        == hashlib.sha256(playlists.state_path().read_bytes()).hexdigest()
    )
    assert all(
        evidence.fingerprint is None and evidence.sha256 is None
        for evidence in plan.authoring_evidence
        if not evidence.present
    )
    assert len(plan.captures) == 2
    for capture in plan.captures:
        assert capture.dynamic_id == f"video:{capture.source_path}"
        assert capture.capture_size == capture.capture_fingerprint[2]
        assert (
            capture.capture_sha256 == hashlib.sha256(capture.capture_path.read_bytes()).hexdigest()
        )
    assert before == {path: path.read_bytes() for path in before}
    assert not deployed_upgrade.journal_path().exists()
    assert not deployed_upgrade.completion_path().exists()


def test_duplicate_marker_key_is_corrupt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    profile = _profile(tmp_path, monkeypatch)
    marker = profile.marker
    marker.write_text(
        '{"schema":1,"schema":1,"plugin":"goober/wall-in-one",'
        '"kind":"automatic-stills","ownership":"managed"}\n',
        encoding="utf-8",
    )
    found = deployed_upgrade.probe()
    assert found.status == "corrupt"
    assert "duplicate-free JSON" in found.detail


@pytest.mark.parametrize("constant", ("NaN", "Infinity", "-Infinity"))
def test_marker_rejects_nonfinite_json_constants(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    constant: str,
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    profile.marker.write_bytes(
        (
            '{"schema":1,"plugin":"goober/wall-in-one",'
            '"kind":"automatic-stills","ownership":' + constant + "}\n"
        ).encode("ascii")
    )

    found = deployed_upgrade.probe()

    assert found.status == "corrupt"
    assert "duplicate-free JSON" in found.detail


@pytest.mark.parametrize(
    "document",
    (
        b'{"value":"\\ud800"}',
        b'{"\\udfff":"value"}',
    ),
)
def test_deployed_json_lone_surrogates_raise_upgrade_error(document: bytes) -> None:
    with pytest.raises(deployed_upgrade.UpgradeError) as raised:
        deployed_upgrade._json_object(document, Path("/marker.json"), label="marker")
    assert raised.value.status == "corrupt"
    assert "duplicate-free JSON" in str(raised.value)


def test_deployed_json_canonicalization_value_error_is_wrapped(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fail_canonicalization(*_args: object, **_kwargs: object) -> str:
        raise ValueError("injected canonicalization failure")

    monkeypatch.setattr(json, "dumps", fail_canonicalization)

    with pytest.raises(deployed_upgrade.UpgradeError, match="duplicate-free JSON"):
        deployed_upgrade._json_object(b'{"schema":1}', Path("/marker.json"), label="marker")


def test_runtime_unknown_field_is_recognizable_corrupt_predecessor(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    source, capture = profile.entries[0]
    paths.runtime_config_path().write_text(
        _runtime(((source, capture),), extra_top_level="unexpected = true"),
        encoding="utf-8",
    )
    found = deployed_upgrade.probe()
    assert found.status == "corrupt"
    assert "top-level shape" in found.detail


@pytest.mark.parametrize(
    "entry",
    (
        {
            "id": "still-entry",
            "kind": "still",
            "still": "/wallpaper.txt",
            "palette": {"kind": "keep"},
        },
        {
            "id": "video-still-entry",
            "kind": "video",
            "still": "/capture.txt",
            "motion": "/wallpaper.mp4",
            "palette": {"kind": "keep"},
        },
        {
            "id": "video-motion-entry",
            "kind": "video",
            "still": "/capture.png",
            "motion": "/wallpaper.txt",
            "palette": {"kind": "keep"},
        },
        {
            "id": "scene-entry",
            "kind": "scene",
            "still": "/representative.txt",
            "scene_id": "431960",
            "palette": {"kind": "keep"},
        },
    ),
)
def test_runtime_media_paths_must_match_current_classification(
    entry: dict[str, object],
) -> None:
    with pytest.raises(deployed_upgrade.UpgradeError) as raised:
        deployed_upgrade._validate_runtime_entry(entry, playlist="All media", ordinal=1)
    assert raised.value.status == "corrupt"
    assert "not classified" in str(raised.value)


def test_forged_video_kind_with_nonvideo_motion_fails_closed(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    source, capture = profile.entries[0]
    nonvideo = source.with_suffix(".txt")
    source.rename(nonvideo)
    paths.runtime_config_path().write_text(
        _runtime(((nonvideo, capture),)),
        encoding="utf-8",
    )

    found = deployed_upgrade.probe()

    assert found.status == "corrupt"
    assert "not classified as video media" in found.detail
    assert not deployed_upgrade.journal_path().exists()


def test_exact_pinned_capture_sizes_enforce_total_before_hashing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch, videos=2)
    first_capture = profile.entries[0][1]
    second_capture = profile.entries[1][1]
    first_capture.write_bytes(b"aaaa")
    second_capture.write_bytes(b"bbbb")
    replacement = tmp_path / "replacement-capture"
    replacement.write_bytes(b"bbbbbbbb")
    monkeypatch.setattr(deployed_upgrade, "MAX_CAPTURE_BYTES", 16)
    monkeypatch.setattr(deployed_upgrade, "MAX_TOTAL_CAPTURE_BYTES", 10)

    original_pin = deployed_upgrade._pin_capture
    replaced = False

    def replace_after_observed_prescan(
        stack: contextlib.ExitStack,
        directory: file_io.PinnedDirectoryContext,
        source: Path,
        capture: Path,
        source_pin: file_io.PinnedPath,
        source_fingerprint: file_io.FileFingerprint,
        *,
        prior_capture_bytes: int,
    ) -> tuple[deployed_upgrade.CapturePlan, file_io.PinnedPath]:
        nonlocal replaced
        if not replaced:
            os.replace(replacement, second_capture)
            replaced = True
        return original_pin(
            stack,
            directory,
            source,
            capture,
            source_pin,
            source_fingerprint,
            prior_capture_bytes=prior_capture_bytes,
        )

    original_hash = file_io.hash_pinned_regular
    hashed: list[str] = []

    def record_hash(
        pinned: file_io.PinnedPath,
        *,
        expected_fingerprint: file_io.FileFingerprint | None = None,
        maximum_bytes: int | None = None,
    ) -> tuple[int, str]:
        hashed.append(pinned.path.name)
        return original_hash(
            pinned,
            expected_fingerprint=expected_fingerprint,
            maximum_bytes=maximum_bytes,
        )

    monkeypatch.setattr(deployed_upgrade, "_pin_capture", replace_after_observed_prescan)
    monkeypatch.setattr(file_io, "hash_pinned_regular", record_hash)

    found = deployed_upgrade.probe()

    assert replaced
    assert found.status == "corrupt"
    assert "total bound" in found.detail
    assert hashed == [first_capture.name]


def test_two_same_stem_videos_cannot_share_one_basename_capture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    root = profile.root
    automatic = profile.automatic
    first = root / "one" / "clip.mp4"
    second = root / "two" / "clip.mp4"
    first.parent.mkdir()
    second.parent.mkdir()
    first.write_bytes(b"one")
    second.write_bytes(b"two")
    capture = automatic / "clip.png"
    capture.write_bytes(b"png")
    paths.runtime_config_path().write_text(
        _runtime(((first, capture), (second, capture))),
        encoding="utf-8",
    )
    found = deployed_upgrade.probe()
    assert found.status == "conflict"
    assert "claim" in found.detail or "basename capture" in found.detail


def test_video_source_with_symlink_ancestor_is_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    root = profile.root
    automatic = profile.automatic
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "linked.mp4").write_bytes(b"video")
    (root / "linked").symlink_to(outside, target_is_directory=True)
    source = root / "linked" / "linked.mp4"
    capture = automatic / "linked.png"
    capture.write_bytes(b"png")
    paths.runtime_config_path().write_text(_runtime(((source, capture),)), encoding="utf-8")
    found = deployed_upgrade.probe()
    assert found.status == "corrupt"
    assert "pin" in found.detail or "symbolic" in found.detail


def test_faulted_current_store_blocks_ready(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _profile(tmp_path, monkeypatch)
    playlists.state_path().write_text("not json", encoding="utf-8")
    found = deployed_upgrade.probe()
    assert found.status == "corrupt"
    assert "Playlists" in found.detail


@pytest.mark.parametrize(
    "kind",
    (
        "pairings",
        "playlists",
        "schedules",
        "displays",
        "favourites",
        "pending-removals",
    ),
)
def test_group_writable_authoring_state_blocks_deployed_upgrade(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    kind: str,
) -> None:
    _profile(tmp_path, monkeypatch)
    targets = {
        "pairings": pairings.state_path(),
        "playlists": playlists.state_path(),
        "schedules": schedules.state_path(),
        "displays": displays.state_path(),
        "favourites": favourites.state_path(),
        "pending-removals": removals.state_path(),
    }
    target = targets[kind]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("{}\n", encoding="utf-8")
    target.chmod(0o620)

    found = deployed_upgrade.probe()

    assert found.status == "corrupt"
    assert target.name in found.detail
    assert "non-group/world-writable" in found.detail


def test_multiply_linked_authoring_state_blocks_deployed_upgrade(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _profile(tmp_path, monkeypatch)
    target = pairings.state_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("{}\n", encoding="utf-8")
    target.chmod(0o600)
    target.with_name("pairings-alias.json").hardlink_to(target)

    found = deployed_upgrade.probe()

    assert found.status == "corrupt"
    assert "single-link" in found.detail


def test_present_authoring_generation_is_retained_through_store_open(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _profile(tmp_path, monkeypatch, named_playlist=True)
    target = playlists.state_path()
    replacement = tmp_path / "replacement-playlists.json"
    replacement.write_bytes(target.read_bytes())
    original_read = playlists._read
    replaced = False

    def replace_after_read(path: Path) -> tuple[dict[str, playlists.Playlist], str | None]:
        nonlocal replaced
        result = original_read(path)
        if path == target and not replaced:
            os.replace(replacement, target)
            replaced = True
        return result

    monkeypatch.setattr(playlists, "_read", replace_after_read)

    found = deployed_upgrade.probe()

    assert replaced
    assert found.status == "corrupt"
    assert "changed during detection" in found.detail


def test_observed_authoring_absence_is_revalidated_after_store_open(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _profile(tmp_path, monkeypatch)
    target = favourites.state_path()
    original_read = favourites._read
    appeared = False

    def create_after_absent_read(path: Path) -> tuple[favourites.Favourites, str | None]:
        nonlocal appeared
        result = original_read(path)
        if path == target and not appeared:
            favourites.save(favourites.Favourites(), path)
            appeared = True
        return result

    monkeypatch.setattr(favourites, "_read", create_after_absent_read)

    found = deployed_upgrade.probe()

    assert appeared
    assert found.status == "conflict"
    assert "appeared during" in found.detail


def test_nonempty_pending_removals_block_deployed_upgrade(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    source = profile.root / "pending.png"
    source.write_bytes(b"pending removal")
    status = source.stat()
    removals.Store.open().prepare(
        library_model.MediaItem(
            source,
            library_model.Kind.STILL,
            status.st_size,
            status.st_mtime_ns,
        ),
        (profile.root,),
    )

    found = deployed_upgrade.probe()

    assert found.status == "conflict"
    assert "Pending Removals contains active removal intents" in found.detail
    assert not deployed_upgrade.journal_path().exists()


def test_explicitly_selected_basename_still_never_becomes_adoption_authority(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    profile = _profile(tmp_path, monkeypatch)
    source, capture = profile.entries[0]
    selected = pairings.Pairing(
        identity=pairings.Identity(pairings.Medium.VIDEO, str(source)),
        still=capture,
        customized=True,
    )
    pairings.save({selected.identity.key: selected})
    before = {
        path: path.read_bytes()
        for path in (
            paths.settings_path(),
            paths.runtime_config_path(),
            pairings.state_path(),
            capture,
        )
    }

    found = deployed_upgrade.probe()

    assert found.status == "conflict"
    assert "explicitly selected" in found.detail
    assert all(path.read_bytes() == contents for path, contents in before.items())
    assert not deployed_upgrade.journal_path().exists()
    assert not deployed_upgrade.authority_path().exists()
    assert not capture.with_name(capture.name + pairing.SIDECAR_SUFFIX).exists()


@pytest.mark.parametrize(
    "filename",
    (
        deployed_upgrade.JOURNAL_FILENAME,
        deployed_upgrade.AUTHORITY_FILENAME,
        deployed_upgrade.STAGED_RUNTIME_FILENAME,
        deployed_upgrade.COMPLETION_FILENAME,
    ),
)
def test_probe_rejects_random_future_transaction_artifacts(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    filename: str,
) -> None:
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    monkeypatch.setenv("XDG_STATE_HOME", str(tmp_path / "state"))
    state = paths.app_state_dir()
    state.mkdir(parents=True)
    (state / filename).write_text("{}\n", encoding="utf-8")
    assert deployed_upgrade.probe().status == "corrupt"
