from __future__ import annotations

import json
import stat
import tomllib
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import pytest

from tests.test_deployed_upgrade import _entry_id, _old_settings
from wall_in_one import (
    config,
    deployed_upgrade,
    deployed_upgrade_transaction,
    file_io,
    paths,
)
from wall_in_one.library import (
    adopted,
    pairing,
    pairings,
    playlists,
    scan,
    schedules,
    stills,
    workshop,
)
from wall_in_one.library.model import Kind
from wall_in_one.wallpaper import scenes

_KEEP_PALETTE = '{ kind = "keep", mode = "keep" }'
_CUSTOM_PALETTE = '{ kind = "named", source = "community", name = "Catppuccin", mode = "dark" }'


@dataclass(frozen=True, slots=True)
class _IncidentEntry:
    source: Path
    kind: Kind
    still: Path
    scene_id: str = ""
    palette: str = _KEEP_PALETTE


@dataclass(frozen=True, slots=True)
class _IncidentProfile:
    root: Path
    automatic: Path
    workshop_content: Path
    motionbgs: Path
    marker: Path
    ordinary_still: Path
    entries: tuple[_IncidentEntry, ...]
    video_captures: tuple[tuple[Path, Path], ...]
    scene_captures: tuple[tuple[Path, Path], ...]
    authored_playlists: tuple[playlists.Playlist, ...]
    authored_schedules: tuple[schedules.Rule, ...]
    customized_source: Path


def _quote(value: str | Path) -> str:
    return json.dumps(str(value))


def _png(ordinal: int) -> bytes:
    return b"\x89PNG\r\n\x1a\n" + ordinal.to_bytes(2, "big")


def _runtime_entry(entry: _IncidentEntry, identifier: str) -> tuple[str, ...]:
    lines = [
        "",
        "[[playlists.entries]]",
        f"id = {_quote(identifier)}",
        f"kind = {_quote(entry.kind.value)}",
        f"still = {_quote(entry.still)}",
    ]
    if entry.kind is Kind.VIDEO:
        lines.append(f"motion = {_quote(entry.source)}")
    elif entry.kind is Kind.SCENE:
        lines.append(f"scene_id = {_quote(entry.scene_id)}")
    lines.append(f"palette = {entry.palette}")
    return tuple(lines)


def _runtime(
    entries: tuple[_IncidentEntry, ...],
    authored: tuple[playlists.Playlist, ...],
    rules: tuple[schedules.Rule, ...],
) -> str:
    lines = [
        "# Generated by Wall-in-One. Edit the library in the app, not this file.",
        "schema_version = 2",
        'default_playlist = "frog-day"',
        "",
        "[settings]",
        "cycle_interval_seconds = 300",
        "cycle_enabled = false",
        "shuffle = false",
        "dynamics_enabled = true",
        "",
        "[renderer]",
        'noctalia_program = "/usr/bin/noctalia"',
        'niri_program = "/usr/bin/niri"',
        'mpvpaper_program = "/usr/bin/mpvpaper"',
        'linux_wallpaperengine_program = "/usr/bin/linux-wallpaperengine"',
        "own_scene_renderer = true",
        'layer = "background"',
        'video_when_hidden = "pause"',
        "video_hardware_decode = true",
        "video_muted = true",
        "video_volume = 100",
        "scene_fps = 30",
        "scene_muted = true",
        "scene_volume = 100",
        "scene_pause_when_covered = true",
        'scene_scaling = ""',
        'scene_clamp = ""',
        "",
        "[[playlists]]",
        'id = "all-media"',
        'name = "All media"',
    ]
    for entry in entries:
        lines.extend(_runtime_entry(entry, _entry_id(entry.source)))

    by_source = {str(entry.source): entry for entry in entries}
    for playlist in authored:
        lines.extend(
            (
                "",
                "[[playlists]]",
                f"id = {_quote(playlist.id)}",
                f"name = {_quote(playlist.name)}",
            )
        )
        for saved in playlist.entries:
            lines.extend(_runtime_entry(by_source[saved.source], saved.id))

    for rule in rules:
        lines.extend(
            (
                "",
                "[[schedules]]",
                f"id = {_quote(rule.id)}",
                f"playlist = {_quote(rule.playlist)}",
            )
        )
        if rule.months:
            lines.append(
                "months = [" + ", ".join(str(value) for value in sorted(rule.months)) + "]"
            )
        if rule.weekdays:
            lines.append(
                "weekdays = [" + ", ".join(str(value) for value in sorted(rule.weekdays)) + "]"
            )
        if rule.start is not None and rule.end is not None:
            lines.append(f"start = {_quote(schedules.format_time(rule.start))}")
            lines.append(f"end = {_quote(schedules.format_time(rule.end))}")
        lines.append(f"enabled = {str(rule.enabled).lower()}")
    return "\n".join(lines) + "\n"


def _incident_profile(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> _IncidentProfile:
    home = tmp_path / "home"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "config"))
    monkeypatch.setenv("XDG_STATE_HOME", str(tmp_path / "state"))

    root = home / "Pictures" / "Wallpapers"
    automatic = root / "Wall-in-One" / "Automatic Stills"
    motionbgs = root / "Wall-in-One" / "MotionBGS"
    automatic.mkdir(parents=True)
    motionbgs.mkdir(parents=True)

    marker = automatic / ".managed-by-wall-in-one-v1.json"
    marker.write_text(
        json.dumps(
            {
                "schema": 1,
                "plugin": "goober/wall-in-one",
                "kind": "automatic-stills",
                "ownership": "managed",
            }
        )
        + "\n",
        encoding="utf-8",
    )

    video_captures: dict[Path, Path] = {}
    local_sources: list[Path] = []
    for ordinal in range(3):
        source = motionbgs / f"motionbgs-{ordinal:02}.mp4"
        capture = automatic / f"motionbgs-{ordinal:02}.png"
        source.write_bytes(f"sanitized-motionbgs-video-{ordinal}".encode())
        capture.write_bytes(_png(ordinal))
        source.with_name(source.name + pairing.SIDECAR_SUFFIX).write_text(
            json.dumps({pairing.SIDECAR_STILL_KEY: str(capture)}) + "\n",
            encoding="utf-8",
        )
        local_sources.append(source)
        video_captures[source] = capture

    steam_root = home / ".local" / "share" / "Steam"
    workshop_content = steam_root / "steamapps" / "workshop" / "content" / workshop.APP_ID
    workshop_content.mkdir(parents=True)
    for ordinal in range(45):
        item = workshop_content / str(2_000_000_000 + ordinal)
        item.mkdir()
        source = item / f"workshop-{ordinal:02}.mp4"
        preview = item / "preview.png"
        source.write_bytes(f"sanitized-workshop-video-{ordinal}".encode())
        preview.write_bytes(_png(100 + ordinal))
        (item / "project.json").write_text(
            json.dumps(
                {
                    "type": "Video" if ordinal % 8 == 0 else "video",
                    "title": f"Sanitized Workshop video {ordinal:02}",
                    "file": source.name,
                    "preview": preview.name,
                }
            )
            + "\n",
            encoding="utf-8",
        )
        capture = automatic / f"workshop-{ordinal:02}.png"
        capture.write_bytes(_png(ordinal + 3))
        video_captures[source] = capture

    scene_captures: dict[Path, Path] = {}
    for ordinal in range(4):
        scene_id = str(3_000_000_000 + ordinal)
        item = workshop_content / scene_id
        item.mkdir()
        preview = item / "preview.png"
        preview.write_bytes(_png(200 + ordinal))
        (item / "scene.pkg").write_bytes(f"sanitized-scene-{ordinal}".encode())
        (item / "project.json").write_text(
            json.dumps(
                {
                    "type": "scene",
                    "title": f"Sanitized Workshop scene {ordinal:02}",
                    "file": "scene.json",
                    "preview": preview.name,
                }
            )
            + "\n",
            encoding="utf-8",
        )
        capture = automatic / f"{scene_id}.png"
        capture.write_bytes(_png(250 + ordinal))
        scene_captures[item] = capture

    ordinary_still = root / "frog-pond.png"
    ordinary_still.write_bytes(_png(500))

    monkeypatch.setattr(
        workshop,
        "content_directories",
        lambda *_args, **_kwargs: (workshop_content,),
    )

    customized_source = local_sources[0]
    customized = pairings.Pairing(
        identity=pairings.Identity(pairings.Medium.VIDEO, str(customized_source)),
        palette=pairings.PalettePolicy(
            kind="community",
            name="Catppuccin",
            mode=pairings.Mode.DARK,
        ),
        customized=True,
    )
    pairings.save({customized.identity.key: customized})

    legacy_captures = set(video_captures.values()) | set(scene_captures.values())
    scanned = scan.scan(
        (root,),
        records=pairings.load(),
        include_workshop=True,
        workshop_roots=(steam_root,),
    )
    logical_items = tuple(item for item in scanned.items if item.path not in legacy_captures)
    assert len(logical_items) == 53
    assert sum(item.kind is Kind.VIDEO for item in logical_items) == 48
    assert sum(item.kind is Kind.SCENE for item in logical_items) == 4
    assert sum(item.kind is Kind.STILL for item in logical_items) == 1

    entries: list[_IncidentEntry] = []
    for media_item in logical_items:
        if media_item.kind is Kind.STILL:
            entries.append(_IncidentEntry(media_item.path, media_item.kind, media_item.path))
        elif media_item.kind is Kind.VIDEO:
            entries.append(
                _IncidentEntry(
                    media_item.path,
                    media_item.kind,
                    video_captures[media_item.path],
                    palette=(
                        _CUSTOM_PALETTE if media_item.path == customized_source else _KEEP_PALETTE
                    ),
                )
            )
        else:
            entries.append(
                _IncidentEntry(
                    media_item.path,
                    media_item.kind,
                    scene_captures[media_item.path],
                    scene_id=media_item.scene,
                )
            )
    logical_entries = tuple(entries)

    specifications = (
        ("frog-day", "frog day", 16),
        ("evening-moss", "evening moss", 10),
        ("rain-windows", "rain windows", 9),
        ("weekend", "weekend", 8),
        ("winter", "winter", 7),
    )
    customized_entry = next(entry for entry in logical_entries if entry.source == customized_source)
    playlist_entries = (
        customized_entry,
        *(entry for entry in logical_entries if entry is not customized_entry),
    )
    cursor = 0
    authored_by_id: dict[str, playlists.Playlist] = {}
    for identifier, name, count in specifications:
        selected = playlist_entries[cursor : cursor + count]
        cursor += count
        authored_by_id[identifier] = playlists.Playlist(
            id=identifier,
            name=name,
            entries=tuple(
                playlists.Entry(
                    id=f"{identifier}-entry-{ordinal:02}",
                    source=str(entry.source),
                )
                for ordinal, entry in enumerate(selected)
            ),
        )
    assert cursor == 50
    playlists.save(authored_by_id)
    authored_playlists = playlists.Store.open().all()

    authored_schedules = (
        schedules.Rule(
            id="weekday-morning",
            playlist="frog-day",
            weekdays=frozenset({0, 1, 2, 3, 4}),
            start=7 * 60,
            end=12 * 60,
        ),
        schedules.Rule(
            id="summer-weekend-evening",
            playlist="rain-windows",
            months=frozenset({6, 7, 8}),
            weekdays=frozenset({5, 6}),
            start=18 * 60,
            end=23 * 60,
        ),
        schedules.Rule(
            id="winter-disabled",
            playlist="winter",
            months=frozenset({1, 2, 12}),
            enabled=False,
        ),
    )
    schedules.save(authored_schedules)

    paths.settings_path().parent.mkdir(parents=True, exist_ok=True)
    paths.settings_path().write_text(
        _old_settings(active_playlist="frog-day"),
        encoding="utf-8",
    )
    paths.noctalia_settings_path().parent.mkdir(parents=True, exist_ok=True)
    paths.noctalia_settings_path().write_text(
        "[unrelated]\n"
        'directory = "/not/the/wallpaper/root"\n\n'
        "[wallpaper]\n"
        f"directory = {_quote(root)}\n",
        encoding="utf-8",
    )
    paths.runtime_config_path().parent.mkdir(parents=True, exist_ok=True)
    paths.runtime_config_path().write_text(
        _runtime(logical_entries, authored_playlists, authored_schedules),
        encoding="utf-8",
    )
    return _IncidentProfile(
        root=root,
        automatic=automatic,
        workshop_content=workshop_content,
        motionbgs=motionbgs,
        marker=marker,
        ordinary_still=ordinary_still,
        entries=logical_entries,
        video_captures=tuple(video_captures.items()),
        scene_captures=tuple(scene_captures.items()),
        authored_playlists=authored_playlists,
        authored_schedules=authored_schedules,
        customized_source=customized_source,
    )


def _file_snapshot(
    files: Iterable[Path],
) -> dict[Path, tuple[bytes, file_io.FileFingerprint]]:
    return {path: (path.read_bytes(), file_io.file_fingerprint(path.lstat())) for path in files}


def _tree_snapshot(root: Path) -> dict[Path, tuple[bytes, file_io.FileFingerprint]]:
    snapshot: dict[Path, tuple[bytes, file_io.FileFingerprint]] = {}
    for path in sorted(root.rglob("*")):
        status = path.lstat()
        assert not stat.S_ISLNK(status.st_mode)
        if stat.S_ISREG(status.st_mode):
            snapshot[path.relative_to(root)] = (
                path.read_bytes(),
                file_io.file_fingerprint(status),
            )
    return snapshot


def _idempotency_snapshot(profile: _IncidentProfile) -> dict[Path, bytes | None]:
    captures = tuple(capture for _source, capture in profile.video_captures)
    documents = (
        paths.settings_path(),
        paths.runtime_config_path(),
        paths.noctalia_settings_path(),
        profile.marker,
        deployed_upgrade.journal_path(),
        deployed_upgrade.authority_path(),
        deployed_upgrade.staged_runtime_path(),
        deployed_upgrade.completion_path(),
        *(capture.with_name(capture.name + pairing.SIDECAR_SUFFIX) for capture in captures),
    )
    return {
        path: path.read_bytes() if path.is_file() and not path.is_symlink() else None
        for path in documents
    }


def _forbid_decoder(*_args: object, **_kwargs: object) -> None:
    raise AssertionError("the deployed-profile upgrade must not invoke a media decoder")


def test_automatic_upgrade_preserves_sanitized_deployed_profile_in_place(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    profile = _incident_profile(tmp_path, monkeypatch)
    capture_paths = tuple(capture for _source, capture in profile.video_captures)
    scene_capture_paths = tuple(capture for _scene, capture in profile.scene_captures)
    capture_before = _file_snapshot((*capture_paths, *scene_capture_paths))
    motionbgs_before = _tree_snapshot(profile.motionbgs)
    workshop_before = _tree_snapshot(profile.workshop_content)
    marker_before = profile.marker.read_bytes()
    workshop_sources = tuple(
        source
        for source, _capture in profile.video_captures
        if source.is_relative_to(profile.workshop_content)
    )
    motionbgs_sources = tuple(
        source
        for source, _capture in profile.video_captures
        if source.is_relative_to(profile.motionbgs)
    )
    assert len(workshop_sources) == 45
    assert len(motionbgs_sources) == 3
    assert all(
        not source.with_name(source.name + pairing.SIDECAR_SUFFIX).exists()
        for source in workshop_sources
    )
    assert all(
        source.with_name(source.name + pairing.SIDECAR_SUFFIX).is_file()
        for source in motionbgs_sources
    )

    monkeypatch.setattr(stills, "generate", _forbid_decoder)
    monkeypatch.setattr(stills, "capture_scene", _forbid_decoder)
    monkeypatch.setattr(scenes, "screenshot", _forbid_decoder)

    ready = deployed_upgrade.probe()
    assert ready.status == "ready"
    assert ready.counts == deployed_upgrade.UpgradeCounts(
        videos=48,
        captures=48,
        all_media_entries=53,
        playlists=5,
        playlist_entries=50,
        schedules=3,
    )

    first = deployed_upgrade_transaction.ensure()

    assert first.changed and first.status == "complete"
    assert first.counts == ready.counts
    assert deployed_upgrade.probe().status == "complete"
    assert config.load_strict().roots == (profile.root,)
    assert config.load_strict().active_playlist == "frog-day"

    adoption = adopted.load(strict=True)
    assert adoption is not None
    assert adoption.root == profile.root
    assert adoption.automatic_stills == profile.automatic
    assert {
        authority.source_path: authority.capture_path for authority in adoption.authorities
    } == dict(profile.video_captures)
    assert _file_snapshot((*capture_paths, *scene_capture_paths)) == capture_before

    runtime = tomllib.loads(paths.runtime_config_path().read_text(encoding="utf-8"))
    assert runtime["schema_version"] == 4
    assert runtime["default_playlist"] == "frog-day"
    compiled_playlists = runtime["playlists"]
    assert len(compiled_playlists) == 6
    all_media = compiled_playlists[0]
    assert all_media["id"] == "all-media"
    assert all_media["name"] == "All media"
    assert len(all_media["entries"]) == 53

    video_entries = [entry for entry in all_media["entries"] if entry["kind"] == "video"]
    scene_entries = [entry for entry in all_media["entries"] if entry["kind"] == "scene"]
    still_entries = [entry for entry in all_media["entries"] if entry["kind"] == "still"]
    assert len(video_entries) == 48
    assert len(scene_entries) == 4
    assert len(still_entries) == 1
    assert still_entries[0]["still"] == str(profile.ordinary_still)
    assert {Path(entry["motion"]): Path(entry["still"]) for entry in video_entries} == dict(
        profile.video_captures
    )
    assert len({entry["still"] for entry in video_entries}) == 48
    assert {(entry["scene_id"], Path(entry["still"])) for entry in scene_entries} == {
        (scene.name, capture) for scene, capture in profile.scene_captures
    }

    named = compiled_playlists[1:]
    assert len(named) == 5
    assert sum(len(playlist["entries"]) for playlist in named) == 50
    frog_day = next(playlist for playlist in named if playlist["name"] == "frog day")
    assert frog_day["id"] == "frog-day"
    assert len(frog_day["entries"]) == 16
    assert len(runtime["schedules"]) == 3

    customized = next(
        entry
        for entry in all_media["entries"]
        if entry.get("motion") == str(profile.customized_source)
    )
    assert customized["palette"] == {
        "kind": "named",
        "source": "community",
        "name": "Catppuccin",
        "mode": "dark",
    }
    assert any(
        entry.get("motion") == str(profile.customized_source)
        and entry["palette"] == customized["palette"]
        for entry in frog_day["entries"]
    )

    current_library = scan.scan(
        (profile.root,),
        records=pairings.load(),
        include_workshop=True,
        workshop_roots=(),
    )
    assert len(current_library.items) == 53
    assert not ({item.path for item in current_library.items} & set(capture_paths))
    assert not ({item.path for item in current_library.items} & set(scene_capture_paths))
    assert {
        item.path: item.paired_still for item in current_library.items if item.kind is Kind.VIDEO
    } == dict(profile.video_captures)
    assert {
        item.path: item.paired_still for item in current_library.items if item.kind is Kind.SCENE
    } == dict(profile.scene_captures)

    assert _tree_snapshot(profile.motionbgs) == motionbgs_before
    assert _tree_snapshot(profile.workshop_content) == workshop_before
    assert profile.marker.read_bytes() == marker_before

    completed = _idempotency_snapshot(profile)
    second = deployed_upgrade_transaction.ensure()

    assert not second.changed and second.status == "complete"
    assert second.counts == ready.counts
    assert _idempotency_snapshot(profile) == completed
    assert _file_snapshot((*capture_paths, *scene_capture_paths)) == capture_before
    assert _tree_snapshot(profile.motionbgs) == motionbgs_before
    assert _tree_snapshot(profile.workshop_content) == workshop_before
