"""Read-only detection of the deployed schema-2 Python application.

One released Wall-in-One build treated an empty ``roots`` setting as an
instruction to use Noctalia's wallpaper directory.  Current builds deliberately
require explicit root consent.  This module identifies only the exact deployed
state which already exercised that old authority; it never turns an arbitrary
empty setting into permission to use a suggested directory.

Detection is intentionally separate from publication.  :func:`build_plan`
returns byte, generation, digest, and directory-identity evidence which a later
locked writer can compare-and-swap.  No function in this module creates,
replaces, moves, or removes a filesystem entry.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import stat
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Final, Literal

from wall_in_one import config, file_io, paths
from wall_in_one.library import (
    displays,
    favourites,
    model,
    pairings,
    playlists,
    removals,
    schedules,
    state_file,
    workshop,
)
from wall_in_one.library import pairing as pairing_conventions

UpgradeStatus = Literal[
    "absent",
    "current",
    "ready",
    "prepared",
    "complete",
    "conflict",
    "corrupt",
    "in-progress",
]
FailureStatus = Literal["conflict", "corrupt"]
AuthoringKind = Literal[
    "pairings",
    "playlists",
    "schedules",
    "displays",
    "favourites",
    "pending-removals",
]

COMPLETION_FILENAME: Final = "deployed-upgrade-v1.json"
JOURNAL_FILENAME: Final = ".deployed-upgrade-v1.journal.json"
AUTHORITY_FILENAME: Final = "deployed-capture-adoption-v1.json"
STAGED_RUNTIME_FILENAME: Final = ".runtime.toml.deployed-upgrade-v1.stage"

AUTOMATIC_MARKER_FILENAME: Final = ".managed-by-wall-in-one-v1.json"
PLUGIN_ID: Final = "goober/wall-in-one"
MAX_RUNTIME_BYTES: Final = 8 * 1024 * 1024
MAX_NOCTALIA_BYTES: Final = 8 * 1024 * 1024
MAX_MARKER_BYTES: Final = 64 * 1024
MAX_FUTURE_FILE_BYTES: Final = 16 * 1024 * 1024
MAX_CAPTURE_BYTES: Final = 512 * 1024 * 1024
MAX_CAPTURES: Final = 512
MAX_ALL_MEDIA_ENTRIES: Final = 1024
MAX_TOTAL_CAPTURE_BYTES: Final = 2 * 1024 * 1024 * 1024
MAX_PATH_BYTES: Final = 4096
MAX_OPTION_BYTES: Final = 256
MAX_IDENTIFIER_BYTES: Final = 256
MAX_PLAYLIST_NAME_CHARACTERS: Final = 120
MAX_REFERENCE_BYTES: Final = MAX_PLAYLIST_NAME_CHARACTERS * 4

_RUNTIME_HEADER: Final = (
    b"# Generated by Wall-in-One. Edit the library in the app, not this file.\n"
)
_PREDECESSOR_SETTINGS_KEYS: Final = frozenset(
    {
        "roots",
        "opacity",
        "preview_scheme",
        "follow_noctalia_palette",
        "cycle_interval",
        "cycle_enabled",
        "shuffle",
        "dynamics_enabled",
        "video_muted",
        "video_volume",
        "video_when_hidden",
        "cycle_favourites_only",
        "active_playlist",
        "scan_workshop",
        "own_scene_renderer",
        "output",
    }
)
_MARKER_KEYS: Final = frozenset({"schema", "plugin", "kind", "ownership"})
_TOP_LEVEL_KEYS: Final = frozenset(
    {
        "schema_version",
        "default_playlist",
        "settings",
        "renderer",
        "playlists",
        "schedules",
        "displays",
    }
)
_TOP_LEVEL_REQUIRED: Final = frozenset(
    {"schema_version", "default_playlist", "settings", "renderer", "playlists"}
)
_RUNTIME_SETTINGS_KEYS: Final = frozenset(
    {"cycle_interval_seconds", "cycle_enabled", "shuffle", "dynamics_enabled"}
)
_RENDERER_KEYS: Final = frozenset(
    {
        "noctalia_program",
        "niri_program",
        "mpvpaper_program",
        "linux_wallpaperengine_program",
        "own_scene_renderer",
        "layer",
        "video_when_hidden",
        "video_hardware_decode",
        "video_muted",
        "video_volume",
        "scene_fps",
        "scene_muted",
        "scene_volume",
        "scene_pause_when_covered",
        "scene_scaling",
        "scene_clamp",
    }
)
_PLAYLIST_KEYS: Final = frozenset({"id", "name", "entries"})
_ENTRY_REQUIRED_KEYS: Final = frozenset({"id", "kind", "still", "palette"})
_ENTRY_KEYS: Final = _ENTRY_REQUIRED_KEYS | {"motion", "scene_id"}
_SCHEDULE_REQUIRED_KEYS: Final = frozenset({"id", "playlist"})
_SCHEDULE_KEYS: Final = _SCHEDULE_REQUIRED_KEYS | {
    "months",
    "weekdays",
    "start",
    "end",
    "enabled",
}
_DISPLAY_KEYS: Final = frozenset({"connector", "playlist"})


class UpgradeError(Exception):
    """The deployed profile cannot be adopted without guessing."""

    def __init__(self, message: str, *, status: FailureStatus = "corrupt") -> None:
        super().__init__(message)
        self.status = status


@dataclass(frozen=True, slots=True)
class UpgradeCounts:
    videos: int = 0
    captures: int = 0
    all_media_entries: int = 0
    playlists: int = 0
    playlist_entries: int = 0
    schedules: int = 0


@dataclass(frozen=True, slots=True)
class Probe:
    status: UpgradeStatus
    detail: str
    counts: UpgradeCounts = UpgradeCounts()

    @property
    def blocks_authoring(self) -> bool:
        return self.status in ("ready", "prepared", "conflict", "corrupt", "in-progress")


@dataclass(frozen=True, slots=True)
class CapturePlan:
    source_path: Path
    capture_path: Path
    dynamic_id: str
    source_fingerprint: file_io.FileFingerprint
    capture_fingerprint: file_io.FileFingerprint
    capture_size: int
    capture_sha256: str


@dataclass(frozen=True, slots=True)
class AuthoringEvidence:
    """One exact authoring-file generation, or its observed absence."""

    kind: AuthoringKind
    path: Path
    fingerprint: file_io.FileFingerprint | None
    sha256: str | None

    @property
    def present(self) -> bool:
        return self.fingerprint is not None


@dataclass(frozen=True, slots=True)
class UpgradePlan:
    root: Path
    root_identity: file_io.PathIdentity
    automatic_stills: Path
    automatic_stills_identity: file_io.PathIdentity
    settings: config.Settings
    settings_path: Path
    settings_bytes: bytes
    settings_fingerprint: file_io.FileFingerprint
    settings_sha256: str
    runtime_path: Path
    runtime_bytes: bytes
    runtime_fingerprint: file_io.FileFingerprint
    runtime_sha256: str
    noctalia_path: Path
    noctalia_bytes: bytes
    noctalia_fingerprint: file_io.FileFingerprint
    noctalia_sha256: str
    marker_path: Path
    marker_bytes: bytes
    marker_fingerprint: file_io.FileFingerprint
    marker_sha256: str
    authoring_evidence: tuple[AuthoringEvidence, ...]
    captures: tuple[CapturePlan, ...]
    all_media_entry_ids: tuple[str, ...]
    prepared_runtime_bytes: bytes
    counts: UpgradeCounts


@dataclass(frozen=True, slots=True)
class _ObservedFile:
    path: Path
    contents: bytes
    fingerprint: file_io.FileFingerprint

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.contents).hexdigest()


@dataclass(frozen=True, slots=True)
class _AuthoringObservation:
    evidence: AuthoringEvidence
    observed: _ObservedFile | None
    pin: file_io.PinnedPath | None


@dataclass(frozen=True, slots=True)
class _RuntimeEntry:
    id: str
    kind: str
    still: Path
    motion: Path | None
    scene_id: str | None
    palette: Mapping[str, object]


@dataclass(frozen=True, slots=True)
class _RuntimePlaylist:
    id: str
    name: str
    entries: tuple[_RuntimeEntry, ...]


@dataclass(frozen=True, slots=True)
class _RuntimeSchedule:
    id: str
    playlist: str
    months: tuple[int, ...]
    weekdays: tuple[int, ...]
    start: str | None
    end: str | None
    enabled: bool


@dataclass(frozen=True, slots=True)
class _RuntimeDisplay:
    connector: str
    playlist: str


@dataclass(frozen=True, slots=True)
class _RuntimeDocument:
    default_playlist: str
    settings: Mapping[str, object]
    renderer: Mapping[str, object]
    playlists: tuple[_RuntimePlaylist, ...]
    schedules: tuple[_RuntimeSchedule, ...]
    displays: tuple[_RuntimeDisplay, ...]


def completion_path() -> Path:
    return paths.app_state_dir() / COMPLETION_FILENAME


def journal_path() -> Path:
    return paths.app_state_dir() / JOURNAL_FILENAME


def authority_path() -> Path:
    return paths.app_state_dir() / AUTHORITY_FILENAME


def staged_runtime_path() -> Path:
    return paths.app_state_dir() / STAGED_RUNTIME_FILENAME


def _future_presence(path: Path) -> bool:
    try:
        status = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as error:
        raise UpgradeError(f"cannot inspect deployed-upgrade state {path}: {error}") from error
    if (
        not stat.S_ISREG(status.st_mode)
        or status.st_uid != os.getuid()
        or status.st_nlink != 1
        or stat.S_IMODE(status.st_mode) & 0o022
        or status.st_size > MAX_FUTURE_FILE_BYTES
    ):
        raise UpgradeError(f"deployed-upgrade state {path} is not a bounded private regular file")
    return True


def _future_probe() -> Probe | None:
    present = any(
        _future_presence(path)
        for path in (
            completion_path(),
            journal_path(),
            authority_path(),
            staged_runtime_path(),
        )
    )
    if not present:
        return None

    # The write half owns the versioned schemas and their cross-file digests.
    # Presence is never success: a forged `{}` marker must not bypass the
    # deployed-profile boundary merely because it has the reserved filename.
    from wall_in_one import deployed_upgrade_transaction

    return deployed_upgrade_transaction.probe_future()


def _enter_owned_regular(
    stack: contextlib.ExitStack,
    path: Path,
    maximum_bytes: int,
    *,
    label: str,
) -> tuple[_ObservedFile, file_io.PinnedPath]:
    try:
        before = path.lstat()
    except FileNotFoundError:
        raise
    except OSError as error:
        raise UpgradeError(f"cannot inspect {label} {path}: {error}") from error
    if not stat.S_ISREG(before.st_mode):
        raise UpgradeError(f"{label} {path} is not a regular file")
    if before.st_uid != os.getuid() or before.st_nlink != 1 or stat.S_IMODE(before.st_mode) & 0o022:
        raise UpgradeError(
            f"{label} {path} is not a single-link, non-group/world-writable file owned by this user"
        )
    fingerprint = file_io.file_fingerprint(before)
    try:
        pin = stack.enter_context(
            file_io.pin_path(
                path,
                expected_file_type=stat.S_IFREG,
                expected_identity=fingerprint[:2],
                expected_fingerprint=fingerprint,
            )
        )
        contents = file_io.read_pinned_regular_bytes(
            pin,
            maximum_bytes,
            expected_fingerprint=fingerprint,
        )
    except OSError as error:
        raise UpgradeError(f"cannot safely read {label} {path}: {error}") from error
    return _ObservedFile(path, contents, fingerprint), pin


def _same_public_file(observed: _ObservedFile, pin: file_io.PinnedPath, *, label: str) -> None:
    try:
        current = observed.path.lstat()
        current_fingerprint = file_io.file_fingerprint(current)
    except (OSError, ValueError) as error:
        raise UpgradeError(f"{label} {observed.path} changed during detection") from error
    if current_fingerprint != observed.fingerprint or pin.fingerprint != observed.fingerprint:
        raise UpgradeError(f"{label} {observed.path} changed during detection")


def _unique_json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


def _reject_json_constant(value: str) -> object:
    raise ValueError(f"non-finite JSON constant {value!r}")


def _validate_json_canonicalization(document: object) -> None:
    (
        json.dumps(
            document,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def _json_object(contents: bytes, path: Path, *, label: str) -> dict[str, Any]:
    try:
        parsed: object = json.loads(
            contents,
            object_pairs_hook=_unique_json_object,
            parse_constant=_reject_json_constant,
        )
        _validate_json_canonicalization(parsed)
    except (UnicodeError, TypeError, ValueError, RecursionError) as error:
        raise UpgradeError(f"{label} {path} is not duplicate-free JSON") from error
    if not isinstance(parsed, dict):
        raise UpgradeError(f"{label} {path} is not a JSON object")
    return parsed


def _toml_object(contents: bytes, path: Path, *, label: str) -> dict[str, Any]:
    try:
        parsed = tomllib.loads(contents.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError, RecursionError) as error:
        raise UpgradeError(f"{label} {path} is not valid TOML: {error}") from error
    if not isinstance(parsed, dict):  # pragma: no cover - tomllib always returns a dict
        raise UpgradeError(f"{label} {path} is not a TOML table")
    return parsed


def _absolute_path(value: object, *, label: str) -> Path:
    if not isinstance(value, str):
        raise UpgradeError(f"{label} must be a path string")
    try:
        encoded = value.encode("utf-8")
    except UnicodeEncodeError as error:
        raise UpgradeError(f"{label} is not valid UTF-8") from error
    if (
        not value
        or len(encoded) > MAX_PATH_BYTES
        or any(ord(character) < 32 or 0x7F <= ord(character) <= 0x9F for character in value)
    ):
        raise UpgradeError(f"{label} is empty, too long, or contains control characters")
    candidate = Path(value)
    normalized = os.path.normpath(value)
    if not candidate.is_absolute() or value != normalized or candidate != Path(normalized):
        raise UpgradeError(f"{label} is not a normalized absolute path")
    return candidate


def _bounded_text(
    value: object,
    *,
    label: str,
    maximum_bytes: int,
    allow_empty: bool = False,
) -> str:
    if not isinstance(value, str):
        raise UpgradeError(f"{label} must be text")
    try:
        encoded = value.encode("utf-8")
    except UnicodeEncodeError as error:
        raise UpgradeError(f"{label} is not valid UTF-8") from error
    if (
        (not value.strip() and not allow_empty)
        or len(encoded) > maximum_bytes
        or any(ord(character) < 32 or 0x7F <= ord(character) <= 0x9F for character in value)
    ):
        raise UpgradeError(f"{label} is empty, too long, or contains control characters")
    return value


def _boolean(value: object, *, label: str) -> bool:
    if not isinstance(value, bool):
        raise UpgradeError(f"{label} must be a boolean")
    return value


def _integer(value: object, *, label: str, minimum: int, maximum: int) -> int:
    if type(value) is not int or not minimum <= value <= maximum:
        raise UpgradeError(f"{label} must be an integer between {minimum} and {maximum}")
    return value


def _exact_keys(
    raw: Mapping[str, object],
    expected: frozenset[str],
    *,
    label: str,
) -> None:
    if set(raw) != expected:
        missing = sorted(expected - set(raw))
        unknown = sorted(set(raw) - expected)
        detail: list[str] = []
        if missing:
            detail.append("missing " + ", ".join(missing))
        if unknown:
            detail.append("unknown " + ", ".join(unknown))
        raise UpgradeError(f"{label} has an ambiguous shape ({'; '.join(detail)})")


def _mapping(value: object, *, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise UpgradeError(f"{label} must be a TOML table")
    return value


def _sequence(value: object, *, label: str, maximum: int) -> list[object]:
    if not isinstance(value, list):
        raise UpgradeError(f"{label} must be an array")
    if len(value) > maximum:
        raise UpgradeError(f"{label} has more than {maximum} entries")
    return value


def _validate_palette(raw_value: object, *, label: str) -> Mapping[str, object]:
    raw = _mapping(raw_value, label=label)
    kind = _bounded_text(raw.get("kind"), label=f"{label} kind", maximum_bytes=32)
    mode = raw.get("mode", "keep")
    if mode not in ("keep", "dark", "light", "auto"):
        raise UpgradeError(f"{label} has an unknown theme mode {mode!r}")
    if kind == "keep":
        _exact_keys(
            raw, frozenset({"kind", "mode"}) if "mode" in raw else frozenset({"kind"}), label=label
        )
    elif kind == "adaptive":
        expected = {"kind", "scheme"}
        if "mode" in raw:
            expected.add("mode")
        _exact_keys(raw, frozenset(expected), label=label)
        _bounded_text(
            raw.get("scheme"),
            label=f"{label} adaptive scheme",
            maximum_bytes=MAX_OPTION_BYTES,
        )
    elif kind == "named":
        expected = {"kind", "source", "name"}
        if "mode" in raw:
            expected.add("mode")
        _exact_keys(raw, frozenset(expected), label=label)
        if raw.get("source") not in ("builtin", "community", "custom"):
            raise UpgradeError(f"{label} has an unknown named palette source")
        _bounded_text(
            raw.get("name"),
            label=f"{label} palette name",
            maximum_bytes=MAX_OPTION_BYTES,
        )
    else:
        raise UpgradeError(f"{label} has an unknown palette kind {kind!r}")
    return raw


def _validate_runtime_entry(raw_value: object, *, playlist: str, ordinal: int) -> _RuntimeEntry:
    label = f"runtime playlist {playlist!r} entry {ordinal}"
    raw = _mapping(raw_value, label=label)
    if not _ENTRY_REQUIRED_KEYS <= set(raw) <= _ENTRY_KEYS:
        raise UpgradeError(f"{label} has an incomplete or ambiguous shape")
    identifier = _bounded_text(
        raw.get("id"), label=f"{label} id", maximum_bytes=MAX_IDENTIFIER_BYTES
    )
    kind = _bounded_text(raw.get("kind"), label=f"{label} kind", maximum_bytes=16)
    if kind not in ("still", "video", "scene"):
        raise UpgradeError(f"{label} has an unknown kind {kind!r}")
    still = _absolute_path(raw.get("still"), label=f"{label} still")
    if model.classify(still) is not model.Kind.STILL:
        raise UpgradeError(
            f"{label} still {still} is not classified as still media by the current scanner"
        )
    motion_value = raw.get("motion")
    scene_value = raw.get("scene_id")
    motion: Path | None = None
    scene_id: str | None = None
    if kind == "still":
        if motion_value is not None or scene_value is not None:
            raise UpgradeError(f"{label} still entry carries motion or scene_id")
    elif kind == "video":
        if scene_value is not None:
            raise UpgradeError(f"{label} video entry carries scene_id")
        motion = _absolute_path(motion_value, label=f"{label} motion")
        if model.classify(motion) is not model.Kind.VIDEO:
            raise UpgradeError(
                f"{label} motion {motion} is not classified as video media by the current scanner"
            )
    else:
        if motion_value is not None:
            raise UpgradeError(f"{label} scene entry carries motion")
        scene_id = _bounded_text(
            scene_value,
            label=f"{label} scene_id",
            maximum_bytes=MAX_IDENTIFIER_BYTES,
        )
        if not scene_id.isascii() or not scene_id.isdigit():
            raise UpgradeError(f"{label} scene_id must contain only ASCII digits")
    palette = _validate_palette(raw.get("palette"), label=f"{label} palette")
    return _RuntimeEntry(identifier, kind, still, motion, scene_id, palette)


def _validate_runtime_playlist(raw_value: object, ordinal: int) -> _RuntimePlaylist:
    label = f"runtime playlist {ordinal}"
    raw = _mapping(raw_value, label=label)
    _exact_keys(raw, _PLAYLIST_KEYS, label=label)
    identifier = _bounded_text(
        raw.get("id"), label=f"{label} id", maximum_bytes=MAX_IDENTIFIER_BYTES
    )
    name = _bounded_text(
        raw.get("name"),
        label=f"{label} name",
        maximum_bytes=MAX_PLAYLIST_NAME_CHARACTERS * 4,
    )
    if len(name) > MAX_PLAYLIST_NAME_CHARACTERS:
        raise UpgradeError(f"{label} name has more than {MAX_PLAYLIST_NAME_CHARACTERS} characters")
    entries_raw = _sequence(
        raw.get("entries"), label=f"{label} entries", maximum=playlists.MAX_ENTRIES
    )
    entries = tuple(
        _validate_runtime_entry(entry, playlist=name, ordinal=entry_ordinal)
        for entry_ordinal, entry in enumerate(entries_raw, start=1)
    )
    entry_ids = [entry.id for entry in entries]
    if len(set(entry_ids)) != len(entry_ids):
        raise UpgradeError(f"{label} has duplicate entry ids")
    return _RuntimePlaylist(identifier, name, entries)


def _validate_runtime_schedule(raw_value: object, ordinal: int) -> _RuntimeSchedule:
    label = f"runtime schedule {ordinal}"
    raw = _mapping(raw_value, label=label)
    if not _SCHEDULE_REQUIRED_KEYS <= set(raw) <= _SCHEDULE_KEYS:
        raise UpgradeError(f"{label} has an incomplete or ambiguous shape")
    identifier = _bounded_text(
        raw.get("id"), label=f"{label} id", maximum_bytes=MAX_IDENTIFIER_BYTES
    )
    playlist = _bounded_text(
        raw.get("playlist"), label=f"{label} playlist", maximum_bytes=MAX_REFERENCE_BYTES
    )
    months_raw = _sequence(raw.get("months", []), label=f"{label} months", maximum=12)
    months = tuple(
        _integer(value, label=f"{label} month", minimum=1, maximum=12) for value in months_raw
    )
    weekdays_raw = _sequence(raw.get("weekdays", []), label=f"{label} weekdays", maximum=7)
    weekdays = tuple(
        _integer(value, label=f"{label} weekday", minimum=0, maximum=6) for value in weekdays_raw
    )
    start_value = raw.get("start")
    end_value = raw.get("end")
    start: str | None = None
    end: str | None = None
    if (start_value is None) != (end_value is None):
        raise UpgradeError(f"{label} has only half a time window")
    if start_value is not None and end_value is not None:
        start = _time(start_value, label=f"{label} start")
        end = _time(end_value, label=f"{label} end")
    enabled = _boolean(raw.get("enabled", True), label=f"{label} enabled")
    return _RuntimeSchedule(identifier, playlist, months, weekdays, start, end, enabled)


def _time(value: object, *, label: str) -> str:
    if not isinstance(value, str):
        raise UpgradeError(f"{label} must be HH:MM text")
    hours, separator, minutes = value.partition(":")
    if (
        not separator
        or ":" in minutes
        or not hours.isascii()
        or not minutes.isascii()
        or not hours.isdigit()
        or not minutes.isdigit()
    ):
        raise UpgradeError(f"{label} is not HH:MM")
    if int(hours) > 23 or int(minutes) > 59:
        raise UpgradeError(f"{label} is not a time of day")
    return value


def _validate_runtime_display(raw_value: object, ordinal: int) -> _RuntimeDisplay:
    label = f"runtime display {ordinal}"
    raw = _mapping(raw_value, label=label)
    _exact_keys(raw, _DISPLAY_KEYS, label=label)
    connector = _bounded_text(
        raw.get("connector"), label=f"{label} connector", maximum_bytes=MAX_OPTION_BYTES
    )
    playlist = _bounded_text(
        raw.get("playlist"), label=f"{label} playlist", maximum_bytes=MAX_REFERENCE_BYTES
    )
    return _RuntimeDisplay(connector, playlist)


def _validate_runtime(contents: bytes, path: Path, settings: config.Settings) -> _RuntimeDocument:
    if not contents.startswith(_RUNTIME_HEADER):
        raise UpgradeError(f"runtime {path} does not have the predecessor compiler header")
    raw = _toml_object(contents, path, label="runtime")
    if not _TOP_LEVEL_REQUIRED <= set(raw) <= _TOP_LEVEL_KEYS:
        raise UpgradeError(f"runtime {path} has an incomplete or ambiguous top-level shape")
    if (
        _integer(
            raw.get("schema_version"),
            label="runtime schema_version",
            minimum=0,
            maximum=2**32 - 1,
        )
        != 2
    ):
        raise UpgradeError(f"runtime {path} is not predecessor schema 2")
    default_playlist = _bounded_text(
        raw.get("default_playlist"),
        label="runtime default_playlist",
        maximum_bytes=MAX_REFERENCE_BYTES,
    )

    runtime_settings = _mapping(raw.get("settings"), label="runtime settings")
    _exact_keys(runtime_settings, _RUNTIME_SETTINGS_KEYS, label="runtime settings")
    interval = _integer(
        runtime_settings.get("cycle_interval_seconds"),
        label="runtime cycle_interval_seconds",
        minimum=5,
        maximum=2**64 - 1,
    )
    cycle_enabled = _boolean(runtime_settings.get("cycle_enabled"), label="runtime cycle_enabled")
    shuffle = _boolean(runtime_settings.get("shuffle"), label="runtime shuffle")
    dynamics_enabled = _boolean(
        runtime_settings.get("dynamics_enabled"), label="runtime dynamics_enabled"
    )
    if (
        interval != settings.cycle_interval
        or cycle_enabled != settings.cycle_enabled
        or shuffle != settings.shuffle
        or dynamics_enabled != settings.dynamics_enabled
    ):
        raise UpgradeError(
            "schema-2 runtime settings do not match the predecessor settings",
            status="conflict",
        )

    renderer = _mapping(raw.get("renderer"), label="runtime renderer")
    _exact_keys(renderer, _RENDERER_KEYS, label="runtime renderer")
    for key in (
        "noctalia_program",
        "niri_program",
        "mpvpaper_program",
        "linux_wallpaperengine_program",
    ):
        _absolute_path(renderer.get(key), label=f"runtime renderer {key}")
    layer = _bounded_text(
        renderer.get("layer"), label="runtime renderer layer", maximum_bytes=MAX_OPTION_BYTES
    )
    if layer != "background":
        raise UpgradeError("schema-2 runtime renderer layer is not the generated value")
    hidden = renderer.get("video_when_hidden")
    if hidden not in ("pause", "stop", "play"):
        raise UpgradeError("runtime renderer video_when_hidden is invalid")
    video_volume = _integer(
        renderer.get("video_volume"),
        label="runtime renderer video_volume",
        minimum=0,
        maximum=100,
    )
    scene_volume = _integer(
        renderer.get("scene_volume"),
        label="runtime renderer scene_volume",
        minimum=0,
        maximum=100,
    )
    scene_fps = _integer(
        renderer.get("scene_fps"),
        label="runtime renderer scene_fps",
        minimum=1,
        maximum=240,
    )
    generated_renderer = (
        _boolean(renderer.get("own_scene_renderer"), label="runtime own_scene_renderer")
        == settings.own_scene_renderer
        and hidden == settings.video_when_hidden
        and _boolean(renderer.get("video_hardware_decode"), label="runtime video_hardware_decode")
        and _boolean(renderer.get("video_muted"), label="runtime video_muted")
        == settings.video_muted
        and video_volume == settings.video_volume
        and scene_fps == 30
        and _boolean(renderer.get("scene_muted"), label="runtime scene_muted")
        == settings.video_muted
        and scene_volume == settings.video_volume
        and _boolean(
            renderer.get("scene_pause_when_covered"),
            label="runtime scene_pause_when_covered",
        )
        and renderer.get("scene_scaling") == ""
        and renderer.get("scene_clamp") == ""
    )
    if not generated_renderer:
        raise UpgradeError(
            "schema-2 runtime renderer does not match predecessor-generated settings",
            status="conflict",
        )

    raw_playlists = _sequence(
        raw.get("playlists"), label="runtime playlists", maximum=playlists.MAX_PLAYLISTS
    )
    parsed_playlists = tuple(
        _validate_runtime_playlist(value, ordinal)
        for ordinal, value in enumerate(raw_playlists, start=1)
    )
    if not parsed_playlists:
        raise UpgradeError("runtime has no playlists")
    playlist_ids = [playlist.id for playlist in parsed_playlists]
    playlist_names = [playlist.name for playlist in parsed_playlists]
    if len(set(playlist_ids)) != len(playlist_ids):
        raise UpgradeError("runtime has duplicate playlist ids")
    if len(set(playlist_names)) != len(playlist_names):
        raise UpgradeError("runtime has duplicate playlist names")
    references = set(playlist_ids) | set(playlist_names)
    if default_playlist not in references:
        raise UpgradeError("runtime default_playlist does not name a runtime playlist")

    raw_schedules = _sequence(
        raw.get("schedules", []), label="runtime schedules", maximum=schedules.MAX_RULES
    )
    parsed_schedules = tuple(
        _validate_runtime_schedule(value, ordinal)
        for ordinal, value in enumerate(raw_schedules, start=1)
    )
    for rule in parsed_schedules:
        if rule.playlist not in references:
            raise UpgradeError(f"runtime schedule {rule.id!r} names an unknown playlist")

    raw_displays = _sequence(
        raw.get("displays", []), label="runtime displays", maximum=displays.MAX_ENTRIES
    )
    parsed_displays = tuple(
        _validate_runtime_display(value, ordinal)
        for ordinal, value in enumerate(raw_displays, start=1)
    )
    connectors = [display.connector for display in parsed_displays]
    if len(set(connectors)) != len(connectors):
        raise UpgradeError("runtime has duplicate display connectors")
    for display in parsed_displays:
        if display.playlist not in references:
            raise UpgradeError(f"runtime display {display.connector!r} names an unknown playlist")
    return _RuntimeDocument(
        default_playlist,
        runtime_settings,
        renderer,
        parsed_playlists,
        parsed_schedules,
        parsed_displays,
    )


def _settings_candidate(
    stack: contextlib.ExitStack,
) -> tuple[str, _ObservedFile | None, file_io.PinnedPath | None, config.Settings | None]:
    target = paths.settings_path()
    try:
        observed, pin = _enter_owned_regular(
            stack,
            target,
            config.MAX_SETTINGS_BYTES,
            label="settings",
        )
    except FileNotFoundError:
        return "absent", None, None, None
    raw = _toml_object(observed.contents, target, label="settings")
    if set(raw) == _PREDECESSOR_SETTINGS_KEYS:
        roots = raw.get("roots")
        if not isinstance(roots, list) or any(not isinstance(value, str) for value in roots):
            raise UpgradeError("predecessor settings roots must be an array of path strings")
        try:
            config._validate_strict_mapping(raw, target)
        except config.ConfigError as error:
            raise UpgradeError(f"predecessor settings are invalid: {error}") from error
        parsed = config.Settings.from_mapping(raw)
        return ("predecessor" if roots == [] else "current"), observed, pin, parsed
    try:
        config._validate_strict_mapping(raw, target)
    except config.ConfigError as error:
        raise UpgradeError(f"current settings are invalid: {error}") from error
    return "current", observed, pin, config.Settings.from_mapping(raw)


def _runtime_schema_hint() -> int | None:
    target = paths.runtime_config_path()
    try:
        raw = file_io.read_regular_bytes(target, MAX_RUNTIME_BYTES)
    except OSError as error:
        raise UpgradeError(f"cannot safely inspect runtime {target}: {error}") from error
    if raw is None:
        return None
    parsed = _toml_object(raw, target, label="runtime")
    value = parsed.get("schema_version")
    return value if type(value) is int else None


def _orphaned_app_payloads() -> tuple[Path, ...]:
    """Known app state which makes a missing settings file non-fresh."""
    candidates = (
        paths.runtime_config_path(),
        pairings.state_path(),
        playlists.state_path(),
        schedules.state_path(),
        displays.state_path(),
        favourites.state_path(),
        removals.state_path(),
    )
    found: list[Path] = []
    for candidate in candidates:
        try:
            candidate.lstat()
        except FileNotFoundError:
            continue
        except OSError as error:
            raise UpgradeError(f"cannot inspect possible app state {candidate}: {error}") from error
        found.append(candidate)
    return tuple(found)


def _noctalia_root(raw: bytes, target: Path) -> Path:
    document = _toml_object(raw, target, label="Noctalia settings")
    wallpaper = document.get("wallpaper")
    if not isinstance(wallpaper, dict):
        raise UpgradeError("Noctalia settings have no [wallpaper] table")
    if "directory" not in wallpaper:
        raise UpgradeError("Noctalia [wallpaper] has no directory")
    return _absolute_path(
        wallpaper["directory"],
        label="Noctalia [wallpaper].directory",
    )


def _pin_root(
    stack: contextlib.ExitStack,
    root: Path,
) -> tuple[file_io.PinnedDirectoryContext, file_io.PathIdentity, file_io.PathIdentity]:
    managed = root / pairing_conventions.MANAGED_PARENT
    automatic = pairing_conventions.still_directory(root)
    try:
        root_status = root.lstat()
        managed_status = managed.lstat()
        automatic_status = automatic.lstat()
    except OSError as error:
        raise UpgradeError(f"cannot inspect predecessor wallpaper directories: {error}") from error
    for path, status in (
        (root, root_status),
        (managed, managed_status),
        (automatic, automatic_status),
    ):
        if not stat.S_ISDIR(status.st_mode) or status.st_uid != os.getuid():
            raise UpgradeError(f"predecessor directory {path} is not owned by this user")
    root_identity = root_status.st_dev, root_status.st_ino
    automatic_identity = automatic_status.st_dev, automatic_status.st_ino
    try:
        context = stack.enter_context(
            file_io.pin_directory_beneath(
                root,
                automatic,
                expected_root_identity=root_identity,
                expected_directory_identity=automatic_identity,
            )
        )
    except (OSError, ValueError) as error:
        raise UpgradeError(
            f"cannot walk predecessor root and Automatic Stills without symbolic links: {error}"
        ) from error
    pinned_root = os.fstat(context.root_descriptor)
    pinned_automatic = os.fstat(context.directory_descriptor)
    if pinned_root.st_uid != os.getuid() or pinned_automatic.st_uid != os.getuid():
        raise UpgradeError("predecessor root or Automatic Stills changed ownership")
    return context, root_identity, automatic_identity


def _marker_observation(
    stack: contextlib.ExitStack,
    directory: file_io.PinnedDirectoryContext,
) -> tuple[_ObservedFile, file_io.PinnedPath]:
    logical = directory.directory / AUTOMATIC_MARKER_FILENAME
    try:
        before = logical.lstat()
    except OSError as error:
        raise UpgradeError(f"cannot inspect Automatic Stills marker {logical}: {error}") from error
    if (
        not stat.S_ISREG(before.st_mode)
        or before.st_uid != os.getuid()
        or before.st_nlink != 1
        or stat.S_IMODE(before.st_mode) & 0o022
    ):
        raise UpgradeError(f"Automatic Stills marker {logical} is not a private owned regular file")
    fingerprint = file_io.file_fingerprint(before)
    try:
        pin = stack.enter_context(
            file_io.pin_regular_path(
                directory.child(AUTOMATIC_MARKER_FILENAME),
                expected_fingerprint=fingerprint,
            )
        )
        contents = file_io.read_pinned_regular_bytes(
            pin,
            MAX_MARKER_BYTES,
            expected_fingerprint=fingerprint,
        )
    except OSError as error:
        raise UpgradeError(
            f"cannot safely read Automatic Stills marker {logical}: {error}"
        ) from error
    marker = _json_object(contents, logical, label="Automatic Stills marker")
    _exact_keys(marker, _MARKER_KEYS, label="Automatic Stills marker")
    if (
        type(marker.get("schema")) is not int
        or marker["schema"] != 1
        or marker.get("plugin") != PLUGIN_ID
        or marker.get("kind") != "automatic-stills"
        or marker.get("ownership") != "managed"
    ):
        raise UpgradeError("Automatic Stills marker does not have the deployed app identity")
    return _ObservedFile(logical, contents, fingerprint), pin


def _owned_single_link(
    pin: file_io.PinnedPath, *, label: str, nonempty: bool = False
) -> os.stat_result:
    status = pin.status()
    if not stat.S_ISREG(status.st_mode) or status.st_uid != os.getuid() or status.st_nlink != 1:
        raise UpgradeError(f"{label} is not a single-link regular file owned by this user")
    if nonempty and status.st_size == 0:
        raise UpgradeError(f"{label} is empty")
    return status


def _workshop_content_directories() -> tuple[Path, ...]:
    try:
        candidates = workshop.content_directories()
    except OSError as error:  # pragma: no cover - the current scanner is forgiving
        raise UpgradeError(
            f"cannot discover current Workshop content directories: {error}"
        ) from error
    found: dict[file_io.PathIdentity, Path] = {}
    filesystem_root = Path("/")
    filesystem_root_identity = file_io.path_identity(filesystem_root)
    for candidate in candidates:
        path = Path(candidate)
        if not path.is_absolute() or path != Path(os.path.normpath(str(path))):
            raise UpgradeError(f"Workshop content directory is not normalized and absolute: {path}")
        try:
            status = path.lstat()
        except FileNotFoundError:
            continue
        except OSError as error:
            raise UpgradeError(
                f"cannot inspect Workshop content directory {path}: {error}"
            ) from error
        if not stat.S_ISDIR(status.st_mode):
            continue
        identity = status.st_dev, status.st_ino
        try:
            context = file_io.pin_directory_beneath(
                filesystem_root,
                path,
                expected_root_identity=filesystem_root_identity,
                expected_directory_identity=identity,
            )
        except OSError, ValueError:
            # Steam commonly exposes ~/.steam/steam as a symlink alias for the
            # same real library.  It is not migration authority: ignore that
            # alias and retain only a unique path whose complete ancestry can
            # be walked without following links.
            continue
        try:
            context.verify_public()
        except OSError as error:
            raise UpgradeError(f"Workshop content directory {path} changed: {error}") from error
        finally:
            context.close()
        previous = found.get(identity)
        if previous is not None and previous != path:
            raise UpgradeError(
                f"Workshop content directory generation is reachable by two no-link paths: "
                f"{previous} and {path}",
                status="conflict",
            )
        found[identity] = path
    return tuple(found.values())


def _source_scope(source: Path, root: Path, workshop_roots: Sequence[Path]) -> Path:
    if source.is_relative_to(root):
        return root
    matches = [candidate for candidate in workshop_roots if source.is_relative_to(candidate)]
    if len(matches) != 1:
        raise UpgradeError(
            f"video source {source} is neither beneath the predecessor root nor "
            "exactly one current Workshop content directory",
            status="conflict",
        )
    return matches[0]


def _pin_scoped_regular(
    stack: contextlib.ExitStack,
    scope: Path,
    path: Path,
    *,
    label: str,
    nonempty: bool = False,
) -> tuple[file_io.PinnedPath, file_io.FileFingerprint]:
    try:
        scoped = file_io.pin_regular_path_beneath(scope, path)
        pin = stack.enter_context(scoped.source)
        status = _owned_single_link(pin, label=label, nonempty=nonempty)
    except (OSError, ValueError) as error:
        if isinstance(error, UpgradeError):
            raise
        raise UpgradeError(f"cannot pin {label} beneath {scope}: {error}") from error
    return pin, file_io.file_fingerprint(status)


def _scene_source(
    stack: contextlib.ExitStack,
    scene_id: str,
    workshop_roots: Sequence[Path],
    cache: dict[str, Path],
) -> Path:
    cached = cache.get(scene_id)
    if cached is not None:
        return cached
    found: list[Path] = []
    for content in workshop_roots:
        candidate = content / scene_id
        try:
            content_status = content.lstat()
            candidate_status = candidate.lstat()
        except FileNotFoundError:
            continue
        except OSError as error:
            raise UpgradeError(f"cannot inspect Workshop scene {candidate}: {error}") from error
        if not stat.S_ISDIR(content_status.st_mode) or not stat.S_ISDIR(candidate_status.st_mode):
            continue
        try:
            context = file_io.pin_directory_beneath(
                content,
                candidate,
                expected_root_identity=(content_status.st_dev, content_status.st_ino),
                expected_directory_identity=(candidate_status.st_dev, candidate_status.st_ino),
            )
        except (OSError, ValueError) as error:
            raise UpgradeError(f"cannot pin Workshop scene {candidate}: {error}") from error
        if os.fstat(context.directory_descriptor).st_uid != os.getuid():
            context.close()
            raise UpgradeError(f"Workshop scene {candidate} is not owned by this user")
        try:
            context.verify_public()
        except BaseException:
            context.close()
            raise
        stack.enter_context(context)
        found.append(candidate)
    if len(found) != 1:
        raise UpgradeError(
            f"scene id {scene_id!r} does not resolve to exactly one current Workshop directory",
            status="conflict",
        )
    cache[scene_id] = found[0]
    return found[0]


def _entry_source(
    stack: contextlib.ExitStack,
    entry: _RuntimeEntry,
    workshop_roots: Sequence[Path],
    scene_cache: dict[str, Path],
) -> Path:
    if entry.kind == "still":
        return entry.still
    if entry.kind == "video":
        assert entry.motion is not None
        return entry.motion
    assert entry.scene_id is not None
    return _scene_source(stack, entry.scene_id, workshop_roots, scene_cache)


def _entry_hash(source: Path) -> str:
    return hashlib.sha256(os.fsencode(source)).hexdigest()[:16]


def _validate_named_playlists(
    stack: contextlib.ExitStack,
    runtime: _RuntimeDocument,
    fallback: _RuntimePlaylist,
    store: playlists.Store,
    workshop_roots: Sequence[Path],
    scene_cache: dict[str, Path],
) -> None:
    runtime_named = tuple(playlist for playlist in runtime.playlists if playlist is not fallback)
    fallback_by_source = {
        _entry_source(stack, entry, workshop_roots, scene_cache): entry
        for entry in fallback.entries
    }
    current = store.all()
    if len(runtime_named) != len(current):
        raise UpgradeError(
            "schema-2 runtime named playlists do not match current Playlists",
            status="conflict",
        )
    for compiled, authored in zip(runtime_named, current, strict=True):
        if compiled.id != authored.id or compiled.name != authored.name:
            raise UpgradeError(
                f"runtime playlist {compiled.name!r} does not match current "
                "Playlists order/identity",
                status="conflict",
            )
        if len(compiled.entries) != len(authored.entries):
            raise UpgradeError(
                f"runtime playlist {compiled.name!r} does not contain every authored entry",
                status="conflict",
            )
        for resolved, saved in zip(compiled.entries, authored.entries, strict=True):
            source = _entry_source(stack, resolved, workshop_roots, scene_cache)
            if resolved.id != saved.id or str(source) != saved.source:
                raise UpgradeError(
                    f"runtime playlist {compiled.name!r} entry {resolved.id!r} does not match "
                    "current Playlists",
                    status="conflict",
                )
            canonical = fallback_by_source.get(source)
            if canonical is None or (
                resolved.kind,
                resolved.still,
                resolved.motion,
                resolved.scene_id,
                resolved.palette,
            ) != (
                canonical.kind,
                canonical.still,
                canonical.motion,
                canonical.scene_id,
                canonical.palette,
            ):
                raise UpgradeError(
                    f"runtime playlist {compiled.name!r} entry {resolved.id!r} does not "
                    "reuse its exact All Media bundle",
                    status="conflict",
                )


def _validate_schedules(
    runtime: _RuntimeDocument,
    store: schedules.Store,
) -> None:
    current = store.rules
    if len(runtime.schedules) != len(current):
        raise UpgradeError(
            "schema-2 runtime schedules do not match current Schedules",
            status="conflict",
        )
    for compiled, authored in zip(runtime.schedules, current, strict=True):
        start = (
            None
            if authored.start is None
            else f"{authored.start // 60:02d}:{authored.start % 60:02d}"
        )
        end = None if authored.end is None else f"{authored.end // 60:02d}:{authored.end % 60:02d}"
        if (
            authored.connector
            or compiled.id != authored.id
            or compiled.playlist != authored.playlist
            or compiled.months != tuple(sorted(authored.months))
            or compiled.weekdays != tuple(sorted(authored.weekdays))
            or compiled.start != start
            or compiled.end != end
            or compiled.enabled != authored.enabled
        ):
            raise UpgradeError(
                f"runtime schedule {compiled.id!r} does not match current Schedules",
                status="conflict",
            )


def _validate_displays(
    runtime: _RuntimeDocument,
    store: displays.Store,
    settings: config.Settings,
    expected_default: str,
    playlist_ids: set[str],
) -> None:
    expected = store.all()
    if not expected and settings.output:
        expected = ((settings.output, expected_default),)
    if any(playlist not in playlist_ids for _connector, playlist in expected):
        raise UpgradeError("current Displays names a playlist absent from schema-2 runtime")
    compiled = tuple((display.connector, display.playlist) for display in runtime.displays)
    if compiled != expected:
        raise UpgradeError(
            "schema-2 runtime displays do not match current Displays",
            status="conflict",
        )


def _pin_capture(
    stack: contextlib.ExitStack,
    directory: file_io.PinnedDirectoryContext,
    source: Path,
    capture: Path,
    source_pin: file_io.PinnedPath,
    source_fingerprint: file_io.FileFingerprint,
    *,
    prior_capture_bytes: int,
) -> tuple[CapturePlan, file_io.PinnedPath]:
    expected = directory.directory / f"{source.stem}.png"
    if capture != expected or capture.parent != directory.directory:
        raise UpgradeError(
            f"schema-2 video {source} does not use its exact predecessor basename capture",
            status="conflict",
        )
    current_destination = directory.directory / (
        f"{pairing_conventions.automatic_still_stem(source)}.png"
    )
    if current_destination != capture:
        try:
            current_destination.lstat()
        except FileNotFoundError:
            pass
        except OSError as error:
            raise UpgradeError(
                f"cannot inspect current hashed capture destination {current_destination}: {error}"
            ) from error
        else:
            raise UpgradeError(
                f"current hashed capture destination {current_destination} already exists "
                f"beside predecessor capture {capture}; refusing to choose between them",
                status="conflict",
            )
    adoption_sidecar = capture.with_name(capture.name + pairing_conventions.SIDECAR_SUFFIX)
    try:
        adoption_sidecar.lstat()
    except FileNotFoundError:
        pass
    except OSError as error:
        raise UpgradeError(
            f"cannot inspect capture-adoption sidecar destination {adoption_sidecar}: {error}"
        ) from error
    else:
        raise UpgradeError(
            f"capture-adoption sidecar destination {adoption_sidecar} already exists "
            "without a deployed-upgrade journal",
            status="conflict",
        )
    try:
        before = capture.lstat()
    except OSError as error:
        raise UpgradeError(f"cannot inspect predecessor capture {capture}: {error}") from error
    if not stat.S_ISREG(before.st_mode):
        raise UpgradeError(f"predecessor capture {capture} is not a regular file")
    fingerprint = file_io.file_fingerprint(before)
    try:
        pin = stack.enter_context(
            file_io.pin_regular_path(
                directory.child(capture.name),
                expected_fingerprint=fingerprint,
            )
        )
        status = _owned_single_link(pin, label=f"predecessor capture {capture}", nonempty=True)
        if status.st_size > MAX_CAPTURE_BYTES:
            raise UpgradeError(
                f"predecessor capture {capture} exceeds its {MAX_CAPTURE_BYTES}-byte limit"
            )
        if prior_capture_bytes + status.st_size > MAX_TOTAL_CAPTURE_BYTES:
            raise UpgradeError(
                f"predecessor captures exceed the {MAX_TOTAL_CAPTURE_BYTES}-byte total bound"
            )
        size, digest = file_io.hash_pinned_regular(
            pin,
            expected_fingerprint=fingerprint,
            maximum_bytes=status.st_size,
        )
    except OSError as error:
        raise UpgradeError(f"cannot safely hash predecessor capture {capture}: {error}") from error
    if source_pin.fingerprint != source_fingerprint:
        raise UpgradeError(f"video source {source} changed while its capture was hashed")
    return (
        CapturePlan(
            source_path=source,
            capture_path=capture,
            dynamic_id=f"video:{source}",
            source_fingerprint=source_fingerprint,
            capture_fingerprint=fingerprint,
            capture_size=size,
            capture_sha256=digest,
        ),
        pin,
    )


def _pin_video_sidecar(
    stack: contextlib.ExitStack,
    scope: Path,
    source: Path,
    capture: Path,
) -> tuple[Path, file_io.PinnedPath, file_io.FileFingerprint] | None:
    sidecar = source.with_name(source.name + pairing_conventions.SIDECAR_SUFFIX)
    try:
        sidecar.lstat()
    except FileNotFoundError:
        return None
    except OSError as error:
        raise UpgradeError(
            f"cannot inspect predecessor video sidecar {sidecar}: {error}"
        ) from error
    pin, fingerprint = _pin_scoped_regular(
        stack,
        scope,
        sidecar,
        label=f"predecessor video sidecar {sidecar}",
        nonempty=True,
    )
    try:
        raw = file_io.read_pinned_regular_bytes(
            pin,
            pairing_conventions.MAX_SIDECAR_BYTES,
            expected_fingerprint=fingerprint,
        )
    except OSError as error:
        raise UpgradeError(
            f"cannot safely read predecessor video sidecar {sidecar}: {error}"
        ) from error
    document = _json_object(raw, sidecar, label="predecessor video sidecar")
    if set(document) != {pairing_conventions.SIDECAR_STILL_KEY} or document.get(
        pairing_conventions.SIDECAR_STILL_KEY
    ) != str(capture):
        raise UpgradeError(
            f"predecessor video sidecar {sidecar} does not name its exact runtime capture",
            status="conflict",
        )
    return sidecar, pin, fingerprint


def _validate_all_media(
    stack: contextlib.ExitStack,
    runtime: _RuntimeDocument,
    root: Path,
    directory: file_io.PinnedDirectoryContext,
    workshop_roots: Sequence[Path],
    scene_cache: dict[str, Path],
    pairing_store: pairings.Store,
) -> tuple[
    _RuntimePlaylist,
    tuple[CapturePlan, ...],
    tuple[tuple[Path, Path, file_io.PinnedPath, file_io.FileFingerprint], ...],
    tuple[tuple[Path, _RuntimeEntry], ...],
]:
    fallback_matches = [
        playlist
        for playlist in runtime.playlists
        if playlist.id == "all-media" and playlist.name == "All media"
    ]
    if len(fallback_matches) != 1:
        raise UpgradeError("runtime does not have exactly one all-media/All media playlist")
    fallback = fallback_matches[0]
    if runtime.playlists[0] is not fallback:
        raise UpgradeError("runtime all-media is not the predecessor compiler's first playlist")
    if len(fallback.entries) > MAX_ALL_MEDIA_ENTRIES:
        raise UpgradeError(f"runtime all-media has more than {MAX_ALL_MEDIA_ENTRIES} entries")
    video_entries = tuple(entry for entry in fallback.entries if entry.kind == "video")
    if len(video_entries) > MAX_CAPTURES:
        raise UpgradeError(f"schema-2 runtime has more than {MAX_CAPTURES} video captures")
    observed_capture_bytes = 0
    for entry in video_entries:
        try:
            status = entry.still.lstat()
        except OSError as error:
            raise UpgradeError(
                f"cannot bound predecessor capture {entry.still}: {error}"
            ) from error
        if not stat.S_ISREG(status.st_mode) or status.st_size <= 0:
            raise UpgradeError(f"predecessor capture {entry.still} is not a non-empty regular file")
        observed_capture_bytes += status.st_size
        if observed_capture_bytes > MAX_TOTAL_CAPTURE_BYTES:
            raise UpgradeError(
                f"predecessor captures exceed the {MAX_TOTAL_CAPTURE_BYTES}-byte total bound"
            )
    captures: list[CapturePlan] = []
    verifications: list[tuple[Path, Path, file_io.PinnedPath, file_io.FileFingerprint]] = []
    sources: set[Path] = set()
    logical_entries: list[tuple[Path, _RuntimeEntry]] = []
    capture_paths: set[Path] = set()
    pinned_capture_bytes = 0
    for entry in fallback.entries:
        source = _entry_source(stack, entry, workshop_roots, scene_cache)
        if source in sources:
            raise UpgradeError(f"runtime all-media repeats source {source}")
        sources.add(source)
        logical_entries.append((source, entry))
        if entry.id != _entry_hash(source):
            raise UpgradeError(
                f"runtime all-media entry {entry.id!r} is not the predecessor hash of {source}",
                status="conflict",
            )
        if entry.kind == "scene":
            # _scene_source already performed a no-symlink directory walk.  The
            # representative still is separately required to be a live owned
            # regular file under the configured root or current Workshop tree.
            still_scope = _source_scope(entry.still, root, workshop_roots)
            pin, fingerprint = _pin_scoped_regular(
                stack,
                still_scope,
                entry.still,
                label=f"scene still {entry.still}",
                nonempty=True,
            )
            verifications.append((still_scope, entry.still, pin, fingerprint))
            continue
        source_scope = _source_scope(source, root, workshop_roots)
        source_pin, source_fingerprint = _pin_scoped_regular(
            stack,
            source_scope,
            source,
            label=f"runtime source {source}",
            nonempty=entry.kind == "video",
        )
        verifications.append((source_scope, source, source_pin, source_fingerprint))
        if entry.kind == "still":
            continue
        selected = pairing_store.records.get(
            pairings.Identity(pairings.Medium.VIDEO, str(source)).key
        )
        if selected is not None and selected.still == entry.still:
            raise UpgradeError(
                f"predecessor pairing explicitly selected {entry.still} for {source}; "
                "that user choice cannot also become generated-capture deletion authority",
                status="conflict",
            )
        sidecar = _pin_video_sidecar(
            stack,
            source_scope,
            source,
            entry.still,
        )
        if sidecar is not None:
            sidecar_path, sidecar_pin, sidecar_fingerprint = sidecar
            verifications.append((source_scope, sidecar_path, sidecar_pin, sidecar_fingerprint))
        plan, capture_pin = _pin_capture(
            stack,
            directory,
            source,
            entry.still,
            source_pin,
            source_fingerprint,
            prior_capture_bytes=pinned_capture_bytes,
        )
        pinned_capture_bytes += plan.capture_size
        if plan.capture_path in capture_paths:
            raise UpgradeError(
                f"multiple videos claim predecessor capture {plan.capture_path}",
                status="conflict",
            )
        capture_paths.add(plan.capture_path)
        captures.append(plan)
        verifications.append((root, plan.capture_path, capture_pin, plan.capture_fingerprint))
    if not captures:
        raise UpgradeError("schema-2 runtime has no video/capture relationship")
    return fallback, tuple(captures), tuple(verifications), tuple(logical_entries)


def _verify_scoped_regular(
    scope: Path,
    logical: Path,
    pin: file_io.PinnedPath,
    expected: file_io.FileFingerprint,
) -> None:
    try:
        verification = file_io.pin_regular_path_beneath(scope, logical)
    except (OSError, ValueError) as error:
        raise UpgradeError(f"{logical} changed or gained a symbolic-link ancestor") from error
    try:
        if verification.source.fingerprint != expected or pin.fingerprint != expected:
            raise UpgradeError(f"{logical} changed during deployed-upgrade detection")
    finally:
        verification.source.close()


def _validate_store_fault(label: str, fault: str | None) -> None:
    if fault is not None:
        raise UpgradeError(f"current {label} store is not safe to use: {fault}")


def _authoring_specs() -> tuple[tuple[AuthoringKind, Path, int, str], ...]:
    """The canonical journal order for every current authoring document."""
    return (
        ("pairings", pairings.state_path(), pairings.MAX_STATE_BYTES, "Pairings"),
        ("playlists", playlists.state_path(), playlists.MAX_STATE_BYTES, "Playlists"),
        ("schedules", schedules.state_path(), schedules.MAX_STATE_BYTES, "Schedules"),
        ("displays", displays.state_path(), displays.MAX_STATE_BYTES, "Displays"),
        ("favourites", favourites.state_path(), favourites.MAX_STATE_BYTES, "Favourites"),
        (
            "pending-removals",
            removals.state_path(),
            removals.MAX_STATE_BYTES,
            "Pending Removals",
        ),
    )


def _observe_authoring_files(
    stack: contextlib.ExitStack,
) -> tuple[_AuthoringObservation, ...]:
    observations: list[_AuthoringObservation] = []
    for kind, path, maximum, label in _authoring_specs():
        try:
            observed, pin = _enter_owned_regular(
                stack,
                path,
                maximum,
                label=f"current {label} state",
            )
        except FileNotFoundError:
            observations.append(
                _AuthoringObservation(
                    AuthoringEvidence(kind, path, None, None),
                    None,
                    None,
                )
            )
            continue
        observations.append(
            _AuthoringObservation(
                AuthoringEvidence(
                    kind,
                    path,
                    observed.fingerprint,
                    observed.sha256,
                ),
                observed,
                pin,
            )
        )
    return tuple(observations)


def _verify_authoring_files(observations: Sequence[_AuthoringObservation]) -> None:
    for record in observations:
        observed = record.observed
        if observed is None:
            try:
                record.evidence.path.lstat()
            except FileNotFoundError:
                continue
            except OSError as error:
                raise UpgradeError(
                    f"current {record.evidence.kind} state changed from its observed absence: "
                    f"{error}"
                ) from error
            raise UpgradeError(
                f"current {record.evidence.kind} state appeared during deployed-upgrade detection",
                status="conflict",
            )
        pin = record.pin
        if pin is None:  # pragma: no cover - constructor invariant
            raise AssertionError("present authoring evidence has no retained pin")
        _same_public_file(observed, pin, label=f"current {record.evidence.kind} state")


def _open_authoring_stores() -> tuple[
    pairings.Store,
    playlists.Store,
    schedules.Store,
    displays.Store,
    favourites.Store,
    removals.Store,
]:
    pairing_store = pairings.Store.open()
    playlist_store = playlists.Store.open()
    schedule_store = schedules.Store.open()
    display_store = displays.Store.open()
    favourite_store = favourites.Store.open()
    removal_store = removals.Store.open()
    _validate_store_fault("Pairings", pairing_store.fault)
    _validate_store_fault("Playlists", playlist_store.fault)
    _validate_store_fault("Schedules", schedule_store.fault)
    _validate_store_fault("Displays", display_store.fault)
    _validate_store_fault("Favourites", favourite_store.fault)
    _validate_store_fault("Pending Removals", removal_store.fault)
    if removal_store.records:
        raise UpgradeError(
            "current Pending Removals contains active removal intents; finish or recover them "
            "before upgrading",
            status="conflict",
        )
    return (
        pairing_store,
        playlist_store,
        schedule_store,
        display_store,
        favourite_store,
        removal_store,
    )


def _render_prepared_runtime(
    *,
    settings: config.Settings,
    root: Path,
    workshop_roots: Sequence[Path],
    logical_entries: Sequence[tuple[Path, _RuntimeEntry]],
    captures: Sequence[CapturePlan],
    pairing_store: pairings.Store,
    playlist_store: playlists.Store,
    schedule_store: schedules.Store,
    display_store: displays.Store,
    favourite_store: favourites.Store,
    removal_store: removals.Store,
) -> bytes:
    """Dry-render the exact current library before any migration publication.

    The schema-2 document proves what the predecessor last compiled.  It does
    not, by itself, prove that a later file was not added below the old root.
    Scan with the still-open generation evidence and require the complete
    logical library to match before a journal can make that snapshot durable.
    """
    from wall_in_one import runtime_config
    from wall_in_one.library import adopted, scan
    from wall_in_one.session import Session

    target_settings = replace(settings, roots=(root,)).validated()
    authorities = tuple(
        adopted.Authority(
            source_path=capture.source_path,
            capture_path=capture.capture_path,
            source_fingerprint=capture.source_fingerprint,
            capture_fingerprint=capture.capture_fingerprint,
            capture_size=capture.capture_size,
            capture_sha256=capture.capture_sha256,
        )
        for capture in captures
    )

    def exact_scanner(requested_roots: Sequence[Path] | None) -> model.Library:
        resolved = tuple(requested_roots or ())
        if resolved != (root,):
            raise UpgradeError(
                "schema-4 migration preflight requested a different library root",
                status="conflict",
            )
        return scan.scan(
            resolved,
            pairing_store.records,
            include_workshop=target_settings.scan_workshop,
            workshop_content_directories=workshop_roots,
            adoption_candidates=authorities,
        )

    session = Session(
        target_settings,
        scanner=exact_scanner,
        pairing_store=pairing_store,
        playlist_store=playlist_store,
        schedule_store=schedule_store,
        display_store=display_store,
        favourite_store=favourite_store,
        removal_store=removal_store,
    )
    try:
        library = session.refresh(mutate_removals=False)
        if library.skipped:
            raise UpgradeError(
                "current library scan cannot prove a complete predecessor snapshot: "
                + "; ".join(library.skipped[:3]),
                status="conflict",
            )
        expected_shape = tuple(
            (source, model.Kind(entry.kind)) for source, entry in logical_entries
        )
        actual_shape = tuple((item.path, item.kind) for item in library.items)
        if actual_shape != expected_shape:
            raise UpgradeError(
                "current library has additional, missing, or reordered logical media "
                "compared with the schema-2 All Media snapshot",
                status="conflict",
            )
        for item, (_source, entry) in zip(
            library.items,
            logical_entries,
            strict=True,
        ):
            if item.is_moving and item.paired_still != entry.still:
                raise UpgradeError(
                    f"current {entry.kind} {item.path} does not resolve to its exact "
                    f"schema-2 representative still {entry.still}",
                    status="conflict",
                )
        rendered = runtime_config.render(target_settings, session).encode("utf-8")
    except (OSError, runtime_config.RuntimeConfigError) as error:
        raise UpgradeError(
            f"cannot dry-render the exact deployed profile as schema 4: {error}",
            status="conflict",
        ) from error
    finally:
        session.shutdown()
    if not rendered or len(rendered) > runtime_config.MAX_RUNTIME_CONFIG_BYTES:
        raise UpgradeError("dry-rendered schema-4 runtime exceeds its byte bound")
    return rendered


def build_plan() -> UpgradePlan:
    """Build immutable adoption evidence without modifying the profile.

    The returned fingerprints are durable comparison inputs, not live pins.
    Every descriptor is retained through the final public-name revalidation and
    closed before this function returns.
    """
    future = _future_probe()
    if future is not None:
        raise UpgradeError(
            f"cannot build a new deployed-upgrade plan while status is {future.status}: "
            f"{future.detail}",
            status="conflict",
        )
    with contextlib.ExitStack() as stack:
        kind, settings_file, settings_pin, settings = _settings_candidate(stack)
        if (
            kind != "predecessor"
            or settings_file is None
            or settings_pin is None
            or settings is None
        ):
            raise UpgradeError(
                "current settings are not the exact empty-root predecessor profile",
                status="conflict",
            )

        try:
            runtime_file, runtime_pin = _enter_owned_regular(
                stack,
                paths.runtime_config_path(),
                MAX_RUNTIME_BYTES,
                label="schema-2 runtime",
            )
        except FileNotFoundError as error:
            raise UpgradeError("the exact predecessor settings have no runtime document") from error
        runtime = _validate_runtime(runtime_file.contents, runtime_file.path, settings)

        try:
            noctalia_file, noctalia_pin = _enter_owned_regular(
                stack,
                paths.noctalia_settings_path(),
                MAX_NOCTALIA_BYTES,
                label="Noctalia settings",
            )
        except FileNotFoundError as error:
            raise UpgradeError(
                "the exact predecessor settings have no Noctalia settings"
            ) from error
        root = _noctalia_root(noctalia_file.contents, noctalia_file.path)
        directory, root_identity, automatic_identity = _pin_root(stack, root)
        marker_file, marker_pin = _marker_observation(stack, directory)

        authoring_observations = _observe_authoring_files(stack)
        snapshots = {
            observation.evidence.path: (
                None if observation.observed is None else observation.observed.contents
            )
            for observation in authoring_observations
        }
        with state_file.read_snapshots(snapshots):
            (
                pairing_store,
                playlist_store,
                schedule_store,
                display_store,
                favourite_store,
                removal_store,
            ) = _open_authoring_stores()
        _verify_authoring_files(authoring_observations)
        workshop_roots = _workshop_content_directories()
        scene_cache: dict[str, Path] = {}
        fallback, capture_plans, verifications, logical_entries = _validate_all_media(
            stack,
            runtime,
            root,
            directory,
            workshop_roots,
            scene_cache,
            pairing_store,
        )
        _validate_named_playlists(
            stack,
            runtime,
            fallback,
            playlist_store,
            workshop_roots,
            scene_cache,
        )
        playlist_ids = {playlist.id for playlist in runtime.playlists}
        expected_default = (
            settings.active_playlist if settings.active_playlist in playlist_ids else "all-media"
        )
        if runtime.default_playlist != expected_default:
            raise UpgradeError(
                "schema-2 runtime default does not match settings active_playlist",
                status="conflict",
            )
        _validate_schedules(runtime, schedule_store)
        _validate_displays(
            runtime,
            display_store,
            settings,
            expected_default,
            playlist_ids,
        )
        prepared_runtime = _render_prepared_runtime(
            settings=settings,
            root=root,
            workshop_roots=workshop_roots,
            logical_entries=logical_entries,
            captures=capture_plans,
            pairing_store=pairing_store,
            playlist_store=playlist_store,
            schedule_store=schedule_store,
            display_store=display_store,
            favourite_store=favourite_store,
            removal_store=removal_store,
        )

        # A future transaction appearing after the initial check means this
        # unlocked read raced a cooperating upgrader.  Return no stale plan.
        if _future_probe() is not None:
            raise UpgradeError(
                "deployed-upgrade state appeared while detection was running",
                status="conflict",
            )
        directory.verify_public()
        _same_public_file(settings_file, settings_pin, label="settings")
        _same_public_file(runtime_file, runtime_pin, label="runtime")
        _same_public_file(noctalia_file, noctalia_pin, label="Noctalia settings")
        try:
            logical_marker = marker_file.path.lstat()
        except OSError as error:
            raise UpgradeError("Automatic Stills marker changed during detection") from error
        if (
            file_io.file_fingerprint(logical_marker) != marker_file.fingerprint
            or marker_pin.fingerprint != marker_file.fingerprint
        ):
            raise UpgradeError("Automatic Stills marker changed during detection")
        for scope, logical, pin, fingerprint in verifications:
            _verify_scoped_regular(scope, logical, pin, fingerprint)
        _verify_authoring_files(authoring_observations)

        named = [playlist for playlist in runtime.playlists if playlist is not fallback]
        counts = UpgradeCounts(
            videos=len(capture_plans),
            captures=len(capture_plans),
            all_media_entries=len(fallback.entries),
            playlists=len(named),
            playlist_entries=sum(len(playlist.entries) for playlist in named),
            schedules=len(runtime.schedules),
        )
        return UpgradePlan(
            root=root,
            root_identity=root_identity,
            automatic_stills=directory.directory,
            automatic_stills_identity=automatic_identity,
            settings=settings,
            settings_path=settings_file.path,
            settings_bytes=settings_file.contents,
            settings_fingerprint=settings_file.fingerprint,
            settings_sha256=settings_file.sha256,
            runtime_path=runtime_file.path,
            runtime_bytes=runtime_file.contents,
            runtime_fingerprint=runtime_file.fingerprint,
            runtime_sha256=runtime_file.sha256,
            noctalia_path=noctalia_file.path,
            noctalia_bytes=noctalia_file.contents,
            noctalia_fingerprint=noctalia_file.fingerprint,
            noctalia_sha256=noctalia_file.sha256,
            marker_path=marker_file.path,
            marker_bytes=marker_file.contents,
            marker_fingerprint=marker_file.fingerprint,
            marker_sha256=marker_file.sha256,
            authoring_evidence=tuple(
                observation.evidence for observation in authoring_observations
            ),
            captures=capture_plans,
            all_media_entry_ids=tuple(entry.id for entry in fallback.entries),
            prepared_runtime_bytes=prepared_runtime,
            counts=counts,
        )


def probe() -> Probe:
    """Classify the current profile without writing or retaining capabilities."""
    try:
        future = _future_probe()
        if future is not None:
            return future
        with contextlib.ExitStack() as stack:
            kind, _observed, _pin, settings = _settings_candidate(stack)
        if kind == "absent":
            orphaned = _orphaned_app_payloads()
            if orphaned:
                return Probe(
                    "corrupt",
                    "Wall-in-One state exists without its settings: "
                    + ", ".join(str(path) for path in orphaned),
                )
            return Probe("absent", "no Wall-in-One settings have been created")
        if kind == "current":
            if settings is not None and not settings.roots and _runtime_schema_hint() == 2:
                return Probe(
                    "conflict",
                    "current empty-root settings coexist with a schema-2 predecessor runtime",
                )
            return Probe("current", "settings already use the current explicit-root contract")
        plan = build_plan()
        return Probe(
            "ready",
            f"the deployed schema-2 profile can resume with explicit root {plan.root}",
            plan.counts,
        )
    except UpgradeError as error:
        return Probe(error.status, str(error))
    except (OSError, ValueError) as error:
        return Probe("corrupt", f"cannot safely inspect the deployed profile: {error}")
