"""One-way, no-overwrite import from the retired Noctalia Luau plugin.

The 0.x Noctalia plugin and this application share a name but not a storage
format.  The plugin kept its authoring document below Noctalia's plugin data
directory, while this application deliberately splits settings, pairings,
playlists, schedules and display assignments into app-owned XDG files.

Migration is conservative for three reasons:

* the legacy bytes are never edited or deleted, so rolling back is possible;
* an import only starts when every current authoring target is absent; and
* each target is installed with a no-replace hard link from a same-directory
  stage.  A small journal makes an interrupted multi-file install resumable
  without accepting a mixture of old and newly generated bytes.

This module has no GTK dependency.  The CLI and the first-run GUI use the same
probe and transaction rather than maintaining two subtly different upgrades.
"""

from __future__ import annotations

import hashlib
import json
import os
import stat
import string
import threading
import tomllib
from collections.abc import Iterator
from contextlib import ExitStack, contextmanager
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Final, Literal

from wall_in_one import config, file_io, paths
from wall_in_one.library import (
    displays,
    favourites,
    pairings,
    playlists,
    removals,
    schedules,
    state_file,
    workshop,
)
from wall_in_one.library import pairing as pairing_conventions
from wall_in_one.library.model import Kind, classify
from wall_in_one.providers import credentials
from wall_in_one.providers.base import ProviderError
from wall_in_one.providers.wallhaven import normalise_api_key
from wall_in_one.theme import noctalia
from wall_in_one.wallpaper import renderer, scenes

LEGACY_PLUGIN_ID: Final = "goober/wall-in-one"
LEGACY_CONFIG_FILENAME: Final = "config.json"
LEGACY_RUNTIME_FILENAME: Final = "runtime.json"
LEGACY_MAX_DOCUMENT_BYTES: Final = 8 * 1024 * 1024
LEGACY_MAX_SETTINGS_BYTES: Final = 8 * 1024 * 1024
MIGRATION_VERSION: Final = 1
MARKER_FILENAME: Final = "legacy-migration-v1.json"
REPORT_FILENAME: Final = "legacy-migration-v1.md"
JOURNAL_FILENAME: Final = ".legacy-migration-v1.journal.json"
MAX_JOURNAL_BYTES: Final = 1024 * 1024
MAX_REPORT_BYTES: Final = 4 * 1024 * 1024
MAX_RECORDED_PATH_BYTES: Final = 4096
MAX_RECORDED_SCHEMA_ABS: Final = 2_147_483_647
MAX_LEGACY_OUTPUTS: Final = 64
MAX_LEGACY_PLAYLISTS: Final = playlists.MAX_AUTHORED_PLAYLISTS
MAX_LEGACY_ENTRIES: Final = playlists.MAX_ENTRIES
MIGRATION_LOCK_TIMEOUT_SECONDS: Final = 60.0
_PROFILE_GATE = threading.RLock()
_PROFILE_DEPTH = threading.local()
LEGACY_SCALING_MAP: Final[dict[str, str]] = {
    "default": "",
    "stretch": "stretch",
    "fit": "fit",
    "fill": "fill",
}
LEGACY_CLAMP_MAP: Final[dict[str, str]] = {
    "clamp": "clamp",
    "border": "border",
    "repeat": "repeat",
}

ProbeStatus = Literal[
    "absent",
    "ready",
    "conflict",
    "corrupt",
    "in-progress",
    "imported",
    "declined",
]


class MigrationError(Exception):
    """Legacy authoring could not be imported without guessing or overwriting."""


@dataclass(frozen=True, slots=True)
class Probe:
    status: ProbeStatus
    detail: str
    source: Path
    schema: int | None = None
    playlists: int = 0
    outputs: int = 0
    conflicts: tuple[Path, ...] = ()

    @property
    def needs_decision(self) -> bool:
        return self.status in ("ready", "conflict", "corrupt", "in-progress")


@dataclass(frozen=True, slots=True)
class Outcome:
    changed: bool
    detail: str
    report: Path | None = None


@dataclass(frozen=True, slots=True)
class _LegacySource:
    directory: Path
    config_path: Path
    runtime_path: Path
    settings_path: Path
    config: dict[str, Any]
    runtime: dict[str, Any]
    plugin_settings: dict[str, Any]
    config_bytes: bytes
    runtime_bytes: bytes
    settings_bytes: bytes
    schema: int

    @property
    def digest(self) -> str:
        digest = hashlib.sha256()
        for document in (self.config_bytes, self.runtime_bytes, self.settings_bytes):
            digest.update(len(document).to_bytes(8, "big"))
            digest.update(document)
        return digest.hexdigest()


@dataclass(frozen=True, slots=True)
class _Converted:
    settings: config.Settings
    pairings: dict[str, pairings.Pairing]
    playlists: dict[str, playlists.Playlist]
    schedules: tuple[schedules.Rule, ...]
    displays: dict[str, str]
    api_key: str
    notes: tuple[str, ...]
    designated_output: str
    legacy_schema: int
    legacy_playlist_count: int
    legacy_output_count: int


@dataclass(frozen=True, slots=True)
class _Target:
    key: str
    path: Path
    contents: bytes
    maximum: int

    @property
    def digest(self) -> str:
        return hashlib.sha256(self.contents).hexdigest()

    @property
    def stage(self) -> Path:
        return self.path.with_name(f".{self.path.name}.legacy-migration-v1.stage")


@dataclass(frozen=True, slots=True)
class _WorkshopResolution:
    path: Path
    medium: pairings.Medium


_IMPORTED_REQUIRED_TARGETS: Final = frozenset(
    {"settings", "pairings", "playlists", "schedules", "displays", "favourites", "report"}
)
_IMPORTED_OPTIONAL_TARGETS: Final = frozenset({"wallhaven-key"})
_JOURNAL_REQUIRED_TARGETS: Final = _IMPORTED_REQUIRED_TARGETS | {"marker"}


def legacy_data_dir() -> Path:
    """The v5 Noctalia plugin's documented state directory."""
    return paths.noctalia_state_dir() / "plugins" / "data" / "goober" / "wall-in-one"


def marker_path() -> Path:
    return paths.app_state_dir() / MARKER_FILENAME


def report_path() -> Path:
    return paths.app_state_dir() / REPORT_FILENAME


def journal_path() -> Path:
    return paths.app_state_dir() / JOURNAL_FILENAME


def _authoring_targets() -> tuple[Path, ...]:
    return (
        paths.settings_path(),
        pairings.state_path(),
        playlists.state_path(),
        schedules.state_path(),
        displays.state_path(),
        favourites.state_path(),
        removals.state_path(),
        credentials.key_path(),
    )


def _existing_authoring() -> tuple[Path, ...]:
    found: list[Path] = []
    # An orphaned report is not authoring, but it is an install target.  Treat
    # it as a conflict up front instead of discovering it after linking part of
    # a new profile.
    for target in (*_authoring_targets(), report_path()):
        try:
            target.lstat()
        except FileNotFoundError:
            continue
        except OSError:
            # An unreadable directory entry is still a conflict.  Import must
            # never reinterpret inability to inspect a target as absence.
            found.append(target)
        else:
            found.append(target)
    return tuple(found)


def _marker_document() -> dict[str, Any] | None:
    target = marker_path()
    try:
        raw = file_io.read_regular_bytes(target, MAX_JOURNAL_BYTES)
    except OSError as error:
        raise MigrationError(f"cannot safely read migration marker {target}: {error}") from error
    if raw is None:
        return None
    document = _json_object(raw, target)
    if type(document.get("version")) is not int or document["version"] != MIGRATION_VERSION:
        raise MigrationError(f"migration marker {target} has an unsupported format")
    disposition = document.get("disposition")
    if disposition not in ("imported", "declined"):
        raise MigrationError(f"migration marker {target} has no valid disposition")
    if disposition == "imported":
        _validate_imported_marker(document, target)
    else:
        _validate_declined_marker(document, target)
    return document


def _validate_imported_marker(document: dict[str, Any], target: Path) -> None:
    required_fields = {
        "version",
        "disposition",
        "legacy_source",
        "legacy_schema",
        "legacy_digest",
        "imported_at",
        "legacy_bytes_modified",
        "report",
        "targets",
    }
    if set(document) != required_fields:
        raise MigrationError(f"imported migration marker {target} is incomplete or ambiguous")
    _recorded_path(document["legacy_source"], "imported marker legacy source")
    schema = document["legacy_schema"]
    if type(schema) is not int or schema not in (1, 2, 3, 4, 5):
        raise MigrationError(f"imported migration marker {target} has an invalid legacy schema")
    _sha256(document["legacy_digest"], "imported marker legacy digest")
    _timestamp(document["imported_at"], "imported marker timestamp")
    if document["legacy_bytes_modified"] is not False:
        raise MigrationError(
            f"imported migration marker {target} does not preserve the legacy source"
        )
    if _recorded_path(document["report"], "imported marker report") != report_path():
        raise MigrationError(f"imported migration marker {target} names a different report")

    raw_targets = document["targets"]
    if not isinstance(raw_targets, dict):
        raise MigrationError(f"imported migration marker {target} has no target manifest")
    names = set(raw_targets)
    allowed = _IMPORTED_REQUIRED_TARGETS | _IMPORTED_OPTIONAL_TARGETS
    if not _IMPORTED_REQUIRED_TARGETS <= names <= allowed:
        raise MigrationError(
            f"imported migration marker {target} has an incomplete target manifest"
        )
    expected_paths = _imported_target_paths()
    for name, raw_entry in raw_targets.items():
        if not isinstance(name, str) or not isinstance(raw_entry, dict):
            raise MigrationError(f"imported migration marker {target} has an invalid target entry")
        if set(raw_entry) != {"path", "sha256"}:
            raise MigrationError(
                f"imported migration marker {target} target {name!r} is incomplete or ambiguous"
            )
        recorded = _recorded_path(raw_entry["path"], f"imported marker target {name!r}")
        if recorded != expected_paths[name]:
            raise MigrationError(
                f"imported migration marker {target} target {name!r} names a different path"
            )
        _sha256(raw_entry["sha256"], f"imported marker target {name!r} digest")

    # Digests describe the immutable completion snapshot, not a permanent pin:
    # normal authoring replaces these files after import.  Their identities
    # must remain present and safe, however, or a bare/forged marker could turn
    # a missing migration into an apparent success.  Clearing a credential is
    # a supported mutation, so an absent optional key remains valid.
    maximums = _imported_target_maximums()
    for name in sorted(names):
        path = expected_paths[name]
        try:
            present = _safe_regular_presence(path, maximums[name])
        except OSError as error:
            raise MigrationError(
                f"imported migration target {name!r} at {path} is not safely readable: {error}"
            ) from error
        if not present and name in _IMPORTED_REQUIRED_TARGETS:
            raise MigrationError(f"imported migration target {name!r} is missing at {path}")


def _validate_declined_marker(document: dict[str, Any], target: Path) -> None:
    required_fields = {
        "version",
        "disposition",
        "legacy_source",
        "legacy_config",
        "legacy_config_sha256",
        "legacy_schema",
        "recorded_at",
        "legacy_bytes_modified",
    }
    if set(document) != required_fields:
        raise MigrationError(f"declined migration marker {target} is incomplete or ambiguous")
    source = _recorded_path(document["legacy_source"], "declined marker legacy source")
    legacy_config = _recorded_path(document["legacy_config"], "declined marker legacy config")
    if legacy_config != source / LEGACY_CONFIG_FILENAME:
        raise MigrationError(f"declined migration marker {target} names a different config")
    _sha256(document["legacy_config_sha256"], "declined marker config digest")
    schema = document["legacy_schema"]
    if schema is not None and (
        type(schema) is not int or not -MAX_RECORDED_SCHEMA_ABS <= schema <= MAX_RECORDED_SCHEMA_ABS
    ):
        raise MigrationError(f"declined migration marker {target} has an invalid legacy schema")
    _timestamp(document["recorded_at"], "declined marker timestamp")
    if document["legacy_bytes_modified"] is not False:
        raise MigrationError(
            f"declined migration marker {target} does not preserve the legacy source"
        )


def _imported_target_paths() -> dict[str, Path]:
    return {
        "settings": paths.settings_path(),
        "pairings": pairings.state_path(),
        "playlists": playlists.state_path(),
        "schedules": schedules.state_path(),
        "displays": displays.state_path(),
        "favourites": favourites.state_path(),
        "report": report_path(),
        "wallhaven-key": credentials.key_path(),
    }


def _imported_target_maximums() -> dict[str, int]:
    return {
        "settings": config.MAX_SETTINGS_BYTES,
        "pairings": pairings.MAX_STATE_BYTES,
        "playlists": playlists.MAX_STATE_BYTES,
        "schedules": schedules.MAX_STATE_BYTES,
        "displays": displays.MAX_STATE_BYTES,
        "favourites": favourites.MAX_STATE_BYTES,
        "report": MAX_REPORT_BYTES,
        "wallhaven-key": 4096,
    }


def probe(*, source_dir: Path | None = None, noctalia_settings: Path | None = None) -> Probe:
    """Describe the upgrade decision without changing either application."""
    candidate = source_dir if source_dir is not None else legacy_data_dir()
    try:
        source = _migration_source(candidate)
    except MigrationError as error:
        return Probe("corrupt", str(error), candidate)
    try:
        marker = _marker_document()
    except MigrationError as error:
        return Probe("conflict", str(error), source, conflicts=(marker_path(),))
    disposition = marker.get("disposition") if marker is not None else None
    if disposition == "imported":
        try:
            journal = _read_journal()
            if journal is not None:
                _validate_completed_journal(marker, journal)
        except MigrationError as error:
            return Probe(
                "conflict",
                str(error),
                source,
                conflicts=(marker_path(), journal_path()),
            )
        return Probe("imported", "legacy authoring was imported", source)
    if disposition == "declined":
        try:
            journal = _read_journal()
        except MigrationError as error:
            return Probe("conflict", str(error), source, conflicts=(journal_path(),))
        if journal is not None:
            return Probe(
                "conflict",
                "a declined migration marker coexists with an interrupted import journal",
                source,
                conflicts=(marker_path(), journal_path()),
            )
        config_path = source / LEGACY_CONFIG_FILENAME
        try:
            source_identity = _source_directory_identity(source, required=True)
            current = file_io.read_regular_bytes(config_path, LEGACY_MAX_DOCUMENT_BYTES)
            if _source_directory_identity(source, required=True) != source_identity:
                raise MigrationError(
                    f"legacy source directory {source} changed while verifying decline"
                )
        except (OSError, MigrationError) as error:
            return Probe(
                "corrupt", f"cannot verify declined legacy source {config_path}: {error}", source
            )
        recorded_source = marker.get("legacy_source") if marker is not None else None
        recorded_digest = marker.get("legacy_config_sha256") if marker is not None else None
        if (
            recorded_source == str(source)
            and current is not None
            and recorded_digest == hashlib.sha256(current).hexdigest()
        ):
            return Probe(
                "declined",
                "legacy import was declined for this exact source; "
                "current authoring is authoritative",
                source,
                schema=(
                    marker.get("legacy_schema")
                    if marker is not None and type(marker.get("legacy_schema")) is int
                    else None
                ),
            )
        return Probe(
            "conflict",
            "the legacy source path or bytes changed after Start fresh was chosen; "
            "the recorded decision was not silently applied to a different source",
            source,
            conflicts=(marker_path(),),
        )

    # A journal is authoritative even if the predecessor config has since
    # disappeared.  Inspect it without following links and prove it still
    # describes this source/build before advertising a resumable transaction.
    try:
        journal = _read_journal()
    except MigrationError as error:
        return Probe("conflict", str(error), source, conflicts=(journal_path(),))
    if journal is not None:
        try:
            legacy = _validate_resumable_journal(
                journal,
                source=source,
                noctalia_settings=noctalia_settings,
            )
        except MigrationError as error:
            return Probe("conflict", str(error), source, conflicts=(journal_path(),))
        return Probe(
            "in-progress",
            "an interrupted legacy import is ready to resume",
            source,
            schema=legacy.schema,
        )

    try:
        source_identity = _source_directory_identity(source, required=False)
    except MigrationError as error:
        return Probe("corrupt", str(error), source)
    if source_identity is None:
        return Probe("absent", f"no legacy config found at {source}", source)

    config_path = source / LEGACY_CONFIG_FILENAME
    try:
        config_bytes = file_io.read_regular_bytes(config_path, LEGACY_MAX_DOCUMENT_BYTES)
    except OSError as error:
        return Probe("corrupt", f"cannot safely read {config_path}: {error}", source)
    try:
        if _source_directory_identity(source, required=True) != source_identity:
            return Probe(
                "corrupt", f"legacy source directory {source} changed while reading", source
            )
    except MigrationError as error:
        return Probe("corrupt", str(error), source)
    if config_bytes is None:
        return Probe("absent", f"no legacy config found at {config_path}", source)

    try:
        legacy = _load_source(source, noctalia_settings)
    except MigrationError as error:
        return Probe("corrupt", str(error), source)
    conflicts = _existing_authoring()
    status: ProbeStatus = "conflict" if conflicts else "ready"
    detail = (
        "current Wall-in-One authoring already exists; automatic import cannot "
        "overwrite or merge it"
        if conflicts
        else "legacy Noctalia Wall-in-One authoring is ready to import"
    )
    raw_playlists = legacy.config.get("playlists")
    raw_outputs = legacy.config.get("outputs")
    if legacy.schema == 2:
        raw_outputs = legacy.config.get("reels")
    return Probe(
        status,
        detail,
        source,
        schema=legacy.schema,
        playlists=len(raw_playlists) if isinstance(raw_playlists, dict) else 0,
        outputs=len(raw_outputs) if isinstance(raw_outputs, dict) else 0,
        conflicts=conflicts,
    )


def require_unattended_safe_locked() -> None:
    """Validate headless authoring while the migration lock is owned."""
    found = probe()
    if found.needs_decision:
        raise MigrationError(
            f"{found.detail}. Open Wall-in-One to choose, or run "
            "`wall-in-one --migrate-legacy` before starting the service"
        )


@contextmanager
def profile_transaction(*, timeout: float = MIGRATION_LOCK_TIMEOUT_SECONDS) -> Iterator[None]:
    """Hold the profile-wide legacy-import exclusion without deciding it.

    The deployed-application upgrade is a separate, automatic compatibility
    boundary.  It must run before the retired-plugin decision guard, while
    still excluding that importer's writes.  Callers which are not performing
    that newer boundary should continue to use :func:`unattended_transaction`.
    """
    with _PROFILE_GATE:
        depth = int(getattr(_PROFILE_DEPTH, "value", 0))
        if depth:
            _PROFILE_DEPTH.value = depth + 1
            try:
                yield
            finally:
                _PROFILE_DEPTH.value = depth
            return
        stack = ExitStack()
        try:
            stack.enter_context(
                state_file.mutation_lock(
                    marker_path(),
                    description="legacy migration",
                    timeout=timeout,
                    process_gate=False,
                )
            )
        except OSError as error:
            stack.close()
            raise MigrationError(
                f"cannot lock the legacy migration transaction: {error}"
            ) from error
        with stack:
            _PROFILE_DEPTH.value = 1
            try:
                yield
            finally:
                _PROFILE_DEPTH.value = 0


@contextmanager
def unattended_transaction(*, timeout: float = MIGRATION_LOCK_TIMEOUT_SECONDS) -> Iterator[None]:
    """Exclude migration for the complete lifetime of one headless writer.

    Merely probing and releasing the marker lock leaves a check/use race: an
    importer can install its journal and initial targets before a health sync
    rewrites Pairings, permanently invalidating the resumable transaction.
    Headless config and health writers hold the same lock as import from the
    guard through their final durable publication.
    """
    with profile_transaction(timeout=timeout):
        require_unattended_safe_locked()
        # Errors from the writer are intentionally outside the acquisition
        # wrapper.  A local I/O failure must retain its own actionable context,
        # not be mislabeled as a migration-lock failure merely because it
        # occurred while exclusion was held.
        yield


def unattended_guard() -> None:
    """Refuse a pristine headless start which would look like a silent reset."""
    with unattended_transaction():
        pass


def decline(*, source_dir: Path | None = None) -> Outcome:
    """Remember an explicit Start fresh/Keep current choice; delete nothing."""
    try:
        with state_file.mutation_lock(
            marker_path(),
            description="legacy migration",
            timeout=MIGRATION_LOCK_TIMEOUT_SECONDS,
            process_gate=False,
        ):
            return _decline_locked(source_dir=source_dir)
    except OSError as error:
        raise MigrationError(f"cannot lock the legacy migration decision: {error}") from error


def _decline_locked(*, source_dir: Path | None = None) -> Outcome:
    source = _migration_source(source_dir if source_dir is not None else legacy_data_dir())
    target = marker_path()
    marker = _marker_document()
    journal = _read_journal()
    if marker is not None:
        if journal is not None:
            if marker["disposition"] == "imported":
                _validate_completed_journal(marker, journal)
            else:
                raise MigrationError(
                    "a declined migration marker coexists with an interrupted import journal"
                )
        imported_report = report_path() if marker["disposition"] == "imported" else None
        return Outcome(False, "a legacy migration decision was already recorded", imported_report)
    if journal is not None:
        raise MigrationError(
            "cannot Start fresh while an interrupted legacy import exists; resume the exact "
            f"transaction described by {journal_path()} or recover it manually"
        )
    config_path = source / LEGACY_CONFIG_FILENAME
    source_identity = _source_directory_identity(source, required=True)
    config_bytes = _required_regular(config_path, LEGACY_MAX_DOCUMENT_BYTES, "legacy config")
    if _source_directory_identity(source, required=True) != source_identity:
        raise MigrationError(f"legacy source directory {source} changed while recording decline")
    try:
        config_document = _json_object(config_bytes, config_path)
    except MigrationError:
        config_document = {}
    schema = config_document.get("schema_version")
    recorded_schema = (
        schema
        if type(schema) is int and -MAX_RECORDED_SCHEMA_ABS <= schema <= MAX_RECORDED_SCHEMA_ABS
        else None
    )
    document = {
        "version": MIGRATION_VERSION,
        "disposition": "declined",
        "legacy_source": str(source),
        "legacy_config": str(config_path),
        "legacy_config_sha256": hashlib.sha256(config_bytes).hexdigest(),
        "legacy_schema": recorded_schema,
        "recorded_at": _now(),
        "legacy_bytes_modified": False,
    }
    try:
        paths.ensure_directory(target.parent)
        _write_no_replace(target, _json_bytes(document))
    except OSError as error:
        raise MigrationError(f"cannot record the migration choice at {target}: {error}") from error
    return Outcome(True, "kept current/fresh authoring; legacy bytes were left untouched")


def postpone(*, source_dir: Path | None = None) -> Outcome:
    """The GUI's Not now choice: deliberately and observably non-persistent."""
    source = _migration_source(source_dir if source_dir is not None else legacy_data_dir())
    return Outcome(
        False,
        f"postponed the legacy decision for {source}; no current or legacy file was changed",
    )


def migrate(*, source_dir: Path | None = None, noctalia_settings: Path | None = None) -> Outcome:
    """Import the retired plugin's authoring into an untouched current profile."""
    try:
        with state_file.mutation_lock(
            marker_path(),
            description="legacy migration",
            timeout=MIGRATION_LOCK_TIMEOUT_SECONDS,
            process_gate=False,
        ):
            return _migrate_locked(
                source_dir=source_dir,
                noctalia_settings=noctalia_settings,
            )
    except OSError as error:
        raise MigrationError(f"cannot lock the legacy migration transaction: {error}") from error


def _migrate_locked(
    *, source_dir: Path | None = None, noctalia_settings: Path | None = None
) -> Outcome:
    source_directory = _migration_source(
        source_dir if source_dir is not None else legacy_data_dir()
    )
    marker = _marker_document()
    disposition = marker.get("disposition") if marker is not None else None
    if disposition == "imported":
        # The imported marker is installed last.  A surviving journal can only
        # mean the process stopped between that durable link and housekeeping,
        # but only an exact marker/journal pair is safe to clean up.
        journal = _read_journal()
        if journal is not None:
            _validate_completed_journal(marker, journal)
        try:
            journal_path().unlink()
            paths.fsync_directory(journal_path().parent)
        except FileNotFoundError:
            pass
        except OSError:
            pass
        return Outcome(False, "legacy authoring was already imported", report_path())
    if disposition == "declined":
        raise MigrationError(
            "legacy import was previously declined; current authoring is authoritative "
            "and was not overwritten"
        )

    journal = _read_journal()
    if journal is None:
        conflicts = _existing_authoring()
        if conflicts:
            joined = ", ".join(str(path) for path in conflicts)
            raise MigrationError(
                "current Wall-in-One authoring already exists, so legacy data was not merged or "
                f"overwritten: {joined}"
            )
        source = _load_source(source_directory, noctalia_settings)
        converted = _convert(source)
        created_at = _now()
        targets = _targets(source, converted, created_at)
        _prepare_directories(bool(converted.api_key))
        _stage_targets(targets)
        journal_document = {
            "version": MIGRATION_VERSION,
            "legacy_source": str(source.directory),
            "legacy_digest": source.digest,
            "created_at": created_at,
            "targets": {target.key: target.digest for target in targets},
        }
        try:
            state_file.write_atomic_text(journal_path(), _json_text(journal_document))
        except OSError as error:
            raise MigrationError(
                f"cannot write migration journal {journal_path()}: {error}"
            ) from error
    else:
        source = _validate_resumable_journal(
            journal,
            source=source_directory,
            noctalia_settings=noctalia_settings,
        )
        converted = _convert(source)
        created_at_value = str(journal["created_at"])
        targets = _targets(source, converted, created_at_value)
        _prepare_directories(bool(converted.api_key))
        _stage_targets(targets, keep_existing=True)

    _install_targets(targets)
    try:
        journal_path().unlink()
        paths.fsync_directory(journal_path().parent)
    except FileNotFoundError:
        pass
    except OSError as error:
        # Every target, including the durable imported marker, is installed.
        # Leaving an exact journal is recoverable and not a failed migration.
        return Outcome(
            True,
            f"imported legacy authoring; could not remove completed journal: {error}",
            report_path(),
        )
    return Outcome(
        True, "imported legacy authoring; legacy bytes were left untouched", report_path()
    )


def _load_source(directory: Path, settings_path: Path | None) -> _LegacySource:
    directory = _migration_source(directory)
    source_identity = _source_directory_identity(directory, required=True)
    config_path = directory / LEGACY_CONFIG_FILENAME
    runtime_path = directory / LEGACY_RUNTIME_FILENAME
    noctalia_path = _recorded_path(
        settings_path if settings_path is not None else paths.noctalia_settings_path(),
        "Noctalia settings path",
    )
    config_bytes = _required_regular(config_path, LEGACY_MAX_DOCUMENT_BYTES, "legacy config")
    runtime_bytes = _optional_regular(runtime_path, LEGACY_MAX_DOCUMENT_BYTES, "legacy runtime")
    settings_bytes = _optional_regular(
        noctalia_path, LEGACY_MAX_SETTINGS_BYTES, "Noctalia settings"
    )
    config_document = _json_object(config_bytes, config_path)
    runtime_document = _json_object(runtime_bytes, runtime_path) if runtime_bytes else {}
    schema_value = config_document.get("schema_version")
    if type(schema_value) is not int or schema_value not in (1, 2, 3, 4, 5):
        raise MigrationError(
            f"{config_path} has unsupported schema {schema_value!r}; "
            "expected legacy schema 1 through 5"
        )
    if not isinstance(config_document.get("gestures"), dict):
        raise MigrationError(f"{config_path} has no valid gestures object")
    plugin_settings: dict[str, Any] = {}
    if settings_bytes:
        try:
            settings_document = tomllib.loads(settings_bytes.decode("utf-8"))
        except (UnicodeDecodeError, tomllib.TOMLDecodeError, RecursionError) as error:
            raise MigrationError(f"{noctalia_path} is not valid UTF-8 TOML: {error}") from error
        outer = settings_document.get("plugin_settings")
        if isinstance(outer, dict):
            selected = outer.get(LEGACY_PLUGIN_ID)
            if isinstance(selected, dict):
                plugin_settings = dict(selected)
    if _source_directory_identity(directory, required=True) != source_identity:
        raise MigrationError(f"legacy source directory {directory} changed while reading")
    return _LegacySource(
        directory=directory,
        config_path=config_path,
        runtime_path=runtime_path,
        settings_path=noctalia_path,
        config=config_document,
        runtime=runtime_document,
        plugin_settings=plugin_settings,
        config_bytes=config_bytes,
        runtime_bytes=runtime_bytes,
        settings_bytes=settings_bytes,
        schema=schema_value,
    )


def _required_regular(path: Path, maximum: int, description: str) -> bytes:
    try:
        document = file_io.read_regular_bytes(path, maximum)
    except OSError as error:
        raise MigrationError(f"cannot safely read {description} {path}: {error}") from error
    if document is None:
        raise MigrationError(f"{description} not found at {path}")
    return document


def _optional_regular(path: Path, maximum: int, description: str) -> bytes:
    try:
        return file_io.read_regular_bytes(path, maximum) or b""
    except OSError as error:
        raise MigrationError(f"cannot safely read {description} {path}: {error}") from error


def _json_object(document: bytes, path: Path) -> dict[str, Any]:
    try:
        value = json.loads(document, object_pairs_hook=_unique_json_object)
    except (UnicodeDecodeError, ValueError, RecursionError) as error:
        raise MigrationError(f"{path} is not readable JSON") from error
    if not isinstance(value, dict):
        raise MigrationError(f"{path} is not a JSON object")
    return value


def _unique_json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    document: dict[str, Any] = {}
    for key, value in pairs:
        if key in document:
            raise ValueError(f"duplicate JSON key {key!r}")
        document[key] = value
    return document


def _migration_source(path: Path) -> Path:
    return _recorded_path(path, "legacy source")


def _source_directory_identity(path: Path, *, required: bool) -> tuple[int, int] | None:
    try:
        info = path.lstat()
    except FileNotFoundError:
        if not required:
            return None
        raise MigrationError(f"legacy source directory not found at {path}") from None
    except OSError as error:
        raise MigrationError(
            f"cannot safely inspect legacy source directory {path}: {error}"
        ) from error
    if stat.S_ISLNK(info.st_mode):
        raise MigrationError(f"legacy source directory {path} is a symbolic link")
    if not stat.S_ISDIR(info.st_mode):
        raise MigrationError(f"legacy source path {path} is not a directory")
    return info.st_dev, info.st_ino


def _recorded_path(value: object, where: str) -> Path:
    if isinstance(value, Path):
        raw = str(value)
    elif isinstance(value, str):
        raw = value
    else:
        raise MigrationError(f"{where} is not a path")
    if not raw or len(raw.encode("utf-8", "surrogatepass")) > MAX_RECORDED_PATH_BYTES:
        raise MigrationError(f"{where} is empty or too long")
    if any(ord(character) < 32 or 0x7F <= ord(character) <= 0x9F for character in raw):
        raise MigrationError(f"{where} contains control characters")
    path = Path(raw)
    if not path.is_absolute():
        raise MigrationError(f"{where} is not an absolute path")
    normalised = Path(os.path.normpath(raw))
    if path != normalised:
        raise MigrationError(f"{where} is not a normalized absolute path")
    return path


def _sha256(value: object, where: str) -> str:
    if (
        not isinstance(value, str)
        or len(value) != 64
        or any(character not in string.hexdigits.lower() for character in value)
    ):
        raise MigrationError(f"{where} is not a lowercase SHA-256 digest")
    return value


def _timestamp(value: object, where: str) -> str:
    if not isinstance(value, str) or not value or len(value) > 64:
        raise MigrationError(f"{where} is not a bounded timestamp")
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as error:
        raise MigrationError(f"{where} is not an ISO-8601 timestamp") from error
    offset = parsed.utcoffset()
    if parsed.tzinfo is None or offset is None:
        raise MigrationError(f"{where} has no UTC offset")
    if offset.total_seconds() != 0:
        raise MigrationError(f"{where} is not recorded in UTC")
    return value


def _safe_regular_presence(path: Path, maximum: int) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as error:
        raise file_io.FileReadError(error.errno, f"cannot inspect {path}: {error}") from error
    if not stat.S_ISREG(info.st_mode):
        raise file_io.FileReadError(f"{path} is not a regular file")
    if info.st_size > maximum:
        raise file_io.FileReadError(f"{path} exceeds its {maximum}-byte limit")
    # A zero-byte prefix still performs the helper's no-follow open/fstat
    # identity check without rereading potentially large authoring stores on
    # every post-migration startup.
    return file_io.read_regular_prefix(path, 0) is not None


def _mapping(value: object, where: str) -> dict[str, Any]:
    if not isinstance(value, dict) or any(not isinstance(key, str) for key in value):
        raise MigrationError(f"{where} is not an object with string keys")
    return dict(value)


def _string(value: object, where: str, *, optional: bool = False) -> str:
    if value is None and optional:
        return ""
    if not isinstance(value, str):
        raise MigrationError(f"{where} is not text")
    clean = value.strip()
    if not clean and not optional:
        raise MigrationError(f"{where} is empty")
    if any(ord(character) < 32 or 0x7F <= ord(character) <= 0x9F for character in clean):
        raise MigrationError(f"{where} contains control characters")
    return clean


def _absolute(value: object, where: str) -> Path:
    path = Path(_string(value, where)).expanduser()
    if not path.is_absolute():
        raise MigrationError(f"{where} is not an absolute path")
    return path


def _integer(value: object, where: str, minimum: int, maximum: int) -> int:
    if type(value) is not int or not minimum <= value <= maximum:
        raise MigrationError(f"{where} must be an integer from {minimum} through {maximum}")
    return value


def _boolean(value: object, where: str, fallback: bool) -> bool:
    if value is None:
        return fallback
    if not isinstance(value, bool):
        raise MigrationError(f"{where} is not a boolean")
    return value


def _convert(source: _LegacySource) -> _Converted:
    notes: list[str] = []
    _report_unmapped_plugin_settings(source.plugin_settings, notes)
    legacy_playlists, legacy_outputs, legacy_pairings = _legacy_authoring(source, notes)
    workshop_paths = _workshop_paths(source.plugin_settings)
    playlist_map, converted_playlists, bundle_candidates = _convert_playlists(
        legacy_playlists, workshop_paths, notes
    )
    designated = _designated_output(legacy_outputs, source.plugin_settings)
    converted_settings = _convert_settings(
        source.plugin_settings,
        legacy_outputs,
        legacy_playlists,
        playlist_map,
        designated,
        notes,
    )
    auto_stills = _legacy_automatic_stills(converted_settings.roots, source.runtime)
    pairing_candidates = [*legacy_pairings.values(), *bundle_candidates]
    converted_pairings = _convert_pairings(
        pairing_candidates,
        auto_stills,
        workshop_paths,
        notes,
    )
    independent = len(legacy_outputs) > 1
    converted_schedules = _convert_schedules(
        legacy_outputs, playlist_map, notes, independent=independent
    )
    converted_displays = _convert_displays(legacy_outputs, playlist_map) if independent else {}
    api_key = _api_key(source.plugin_settings, notes)

    if source.schema < 5:
        notes.append(
            f"The retired plugin's schema {source.schema} was normalized into the "
            "current split stores."
        )
    notes.extend(
        (
            "Legacy favourites were not imported because the Luau application had "
            "no favourites store.",
            "Runtime cursors, shuffle bags, history, pause state, temporary manual "
            "pins, diagnostics, and owned child PIDs were intentionally reset.",
            "Mouse gesture bindings remain Noctalia-plugin configuration and have "
            "no app-owned equivalent.",
        )
    )
    return _Converted(
        settings=converted_settings,
        pairings=converted_pairings,
        playlists=converted_playlists,
        schedules=converted_schedules,
        displays=converted_displays,
        api_key=api_key,
        notes=tuple(dict.fromkeys(notes)),
        designated_output=designated,
        legacy_schema=source.schema,
        legacy_playlist_count=len(legacy_playlists),
        legacy_output_count=len(legacy_outputs),
    )


def _report_unmapped_plugin_settings(plugin: dict[str, Any], notes: list[str]) -> None:
    disabled = [
        name
        for name, key in (("Wallhaven", "use_wallhaven"), ("MotionBGS", "use_motionbgs"))
        if plugin.get(key) is False
    ]
    if disabled:
        notes.append(
            "Legacy provider-disable choices are not current settings; these providers remain "
            "available after import: " + ", ".join(disabled) + "."
        )
    if plugin.get("sync_colors") is False:
        notes.append(
            "Legacy sync_colors=false has no one-to-one current setting. Imported wallpaper "
            "palette policies remain active; review Pairings before first playback."
        )
    provider_defaults: dict[str, object] = {
        "motionbgs_result_limit": 48,
        "motionbgs_cache_minutes": 30,
        "motionbgs_max_download_mb": 256,
        "motionbgs_quality": "hd",
    }
    changed_provider = [
        key
        for key, default in provider_defaults.items()
        if key in plugin and plugin.get(key) != default
    ]
    if changed_provider:
        notes.append(
            "Legacy MotionBGS tuning has no current persisted equivalent and was reset: "
            + ", ".join(changed_provider)
            + "."
        )
    capture_defaults: dict[str, object] = {
        "auto_capture": True,
        "video_frame_second": 1,
        "scene_screenshot_delay": 15,
    }
    changed_capture = [
        key
        for key, default in capture_defaults.items()
        if key in plugin and plugin.get(key) != default
    ]
    if changed_capture:
        notes.append(
            "Legacy capture tuning was reset to the current still generator's policy: "
            + ", ".join(changed_capture)
            + "."
        )
    obsolete = [
        key
        for key in ("backend_binary_path", "video_source", "manual_pair_file", "workshop_id")
        if isinstance(plugin.get(key), str) and plugin[key].strip()
    ]
    if obsolete:
        notes.append(
            "Legacy one-shot/backend plugin fields are not current authoring and were reset: "
            + ", ".join(obsolete)
            + "."
        )
    custom_workshop = plugin.get("workshop_directory")
    if isinstance(custom_workshop, str) and custom_workshop.strip():
        notes.append(
            "The legacy custom Workshop directory was used to resolve installed items during "
            "import, but current Workshop discovery does not persist a custom directory."
        )


def _legacy_authoring(
    source: _LegacySource, notes: list[str]
) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
    document = source.config
    if source.schema == 1:
        return {}, {}, {}
    if source.schema == 2:
        reels = _mapping(document.get("reels"), "legacy reels")
        if len(reels) > MAX_LEGACY_OUTPUTS:
            raise MigrationError(f"legacy config has more than {MAX_LEGACY_OUTPUTS} outputs")
        made: dict[str, dict[str, Any]] = {}
        outputs: dict[str, dict[str, Any]] = {}
        for ordinal, (connector, raw_reel) in enumerate(sorted(reels.items()), start=1):
            clean_connector = _connector(connector, f"legacy reel connector {connector!r}")
            reel = _mapping(raw_reel, f"legacy reel {connector!r}")
            raw_entries = reel.get("entries")
            if not isinstance(raw_entries, list):
                raise MigrationError(f"legacy reel {connector!r} has no entry list")
            identifier = f"legacy-reel-{ordinal}-{_short_hash(clean_connector)}"
            entries: list[dict[str, Any]] = []
            for index, raw in enumerate(raw_entries):
                old = _mapping(raw, f"legacy reel {connector!r} entry {index + 1}")
                kind = _string(old.get("kind"), "legacy reel entry kind")
                source_value = old.get("source")
                if kind == "static":
                    bundle = {
                        "id": f"legacy-entry-{index + 1}",
                        "label": old.get("label") or Path(str(source_value)).name,
                        "media": None,
                        "still": {"mode": "selected", "path": source_value},
                        "theme": {"mode": "auto", "source": "wallpaper", "selection": "m3-content"},
                        "customized": False,
                    }
                elif kind in ("video", "workshop"):
                    still_path = old.get("still_path")
                    still = (
                        {"mode": "selected", "path": still_path}
                        if isinstance(still_path, str) and still_path
                        else {"mode": "automatic"}
                    )
                    bundle = {
                        "id": f"legacy-entry-{index + 1}",
                        "label": old.get("label") or str(source_value),
                        "media": {"kind": kind, "source": source_value},
                        "still": still,
                        "theme": {"mode": "auto", "source": "wallpaper", "selection": "m3-content"},
                        "customized": False,
                    }
                else:
                    raise MigrationError(f"legacy reel entry has unsupported kind {kind!r}")
                entries.append(bundle)
            made[identifier] = {
                "name": f"Migrated · {clean_connector}",
                "order": reel.get("order", "rotate"),
                "interval_seconds": reel.get("interval_seconds", 900),
                "entries": entries,
                "quick_choice": False,
            }
            outputs[clean_connector] = {
                "fallback_playlist": identifier,
                "quick_choice_playlist": "",
                "schedules": [],
                "engines": _default_legacy_engines(),
            }
        notes.append("Legacy per-output reels were converted to named playlists.")
        return made, outputs, {}

    raw_playlists = _mapping(document.get("playlists"), "legacy playlists")
    raw_outputs = _mapping(document.get("outputs"), "legacy outputs")
    raw_pairings = document.get("pairings", {}) if source.schema >= 4 else {}
    converted_playlists = {
        identifier: _mapping(value, f"legacy playlist {identifier!r}")
        for identifier, value in raw_playlists.items()
    }
    converted_outputs = {
        _connector(identifier, f"legacy output {identifier!r}"): _mapping(
            value, f"legacy output {identifier!r}"
        )
        for identifier, value in raw_outputs.items()
    }
    converted_pairings = {
        identifier: _mapping(value, f"legacy pairing {identifier!r}")
        for identifier, value in _mapping(raw_pairings, "legacy pairings").items()
    }
    if len(converted_playlists) > MAX_LEGACY_PLAYLISTS:
        raise MigrationError(f"legacy config has more than {MAX_LEGACY_PLAYLISTS} playlists")
    if len(converted_outputs) > MAX_LEGACY_OUTPUTS:
        raise MigrationError(f"legacy config has more than {MAX_LEGACY_OUTPUTS} outputs")
    return converted_playlists, converted_outputs, converted_pairings


def _convert_playlists(
    legacy: dict[str, dict[str, Any]],
    workshop_paths: dict[str, _WorkshopResolution],
    notes: list[str],
) -> tuple[dict[str, str], dict[str, playlists.Playlist], list[dict[str, Any]]]:
    mapped: dict[str, str] = {}
    converted: dict[str, playlists.Playlist] = {}
    bundles: list[dict[str, Any]] = []
    used_ids: set[str] = set()
    used_names: set[str] = set()
    quick_choices = 0
    total_entries = 0
    for ordinal, old_id in enumerate(sorted(legacy), start=1):
        raw = legacy[old_id]
        raw_name = _string(raw.get("name"), f"legacy playlist {old_id!r} name")
        quick = _boolean(raw.get("quick_choice"), f"legacy playlist {old_id!r} quick_choice", False)
        name_seed = f"Imported quick choice · {raw_name}" if quick else raw_name
        name = _unique_playlist_name(name_seed, used_names)
        identifier = _playlist_id(old_id, ordinal, used_ids, used_names)
        used_ids.add(identifier.casefold())
        used_names.add(name.casefold())
        mapped[old_id] = identifier
        raw_entries = raw.get("entries")
        if not isinstance(raw_entries, list):
            raise MigrationError(f"legacy playlist {old_id!r} has no entry list")
        if len(raw_entries) > MAX_LEGACY_ENTRIES:
            raise MigrationError(
                f"legacy playlist {old_id!r} has more than {MAX_LEGACY_ENTRIES} entries"
            )
        entries: list[playlists.Entry] = []
        entry_ids: set[str] = set()
        for index, raw_entry in enumerate(raw_entries, start=1):
            bundle = _mapping(raw_entry, f"legacy playlist {old_id!r} entry {index}")
            source = _bundle_playback_source(bundle, workshop_paths, notes)
            old_entry_id = _string(bundle.get("id"), f"legacy playlist {old_id!r} entry {index} id")
            entry_id = _entry_id(old_entry_id, old_id, index, entry_ids)
            entry_ids.add(entry_id)
            entries.append(playlists.Entry(entry_id, str(source)))
            bundles.append(bundle)
            total_entries += 1
            if total_entries > playlists.MAX_ENTRIES:
                raise MigrationError(
                    f"legacy playlists have more than {playlists.MAX_ENTRIES} total entries"
                )
        converted[identifier] = playlists.Playlist(identifier, name, tuple(entries))
        if quick:
            quick_choices += 1
    if quick_choices:
        notes.append(
            f"{quick_choices} persisted Quick Choice playlist(s) were retained as "
            "ordinary named playlists; transient active pins were reset."
        )
    return mapped, converted, bundles


def _bundle_playback_source(
    bundle: dict[str, Any],
    workshop_paths: dict[str, _WorkshopResolution],
    notes: list[str],
) -> Path:
    media = bundle.get("media")
    if media is None:
        still = _mapping(bundle.get("still"), "legacy static entry still")
        if _string(still.get("mode"), "legacy static still mode") != "selected":
            raise MigrationError("a legacy static entry has no selected still path")
        path = _absolute(still.get("path"), "legacy static entry path")
        if not path.is_file():
            notes.append(
                "One or more legacy file-backed wallpaper paths are currently missing. "
                "Their absolute paths were preserved for a later remount or manual repair."
            )
        return path
    media_map = _mapping(media, "legacy entry media")
    kind = _string(media_map.get("kind"), "legacy entry media kind")
    if kind == "video":
        path = _absolute(media_map.get("source"), "legacy video source")
        if not path.is_file():
            notes.append(
                "One or more legacy file-backed wallpaper paths are currently missing. "
                "Their absolute paths were preserved for a later remount or manual repair."
            )
        return path
    if kind != "workshop":
        raise MigrationError(f"legacy entry has unsupported media kind {kind!r}")
    identifier = _workshop_id(media_map.get("source"), "legacy Workshop source")
    known = workshop_paths.get(identifier)
    if known is not None:
        return known.path
    fallback = _fallback_workshop_path(identifier)
    workshop_paths[identifier] = _WorkshopResolution(fallback, pairings.Medium.SCENE)
    notes.append(
        f"Workshop item {identifier} was not installed in a discoverable Steam "
        f"library; its playlist entry keeps the expected path {fallback} and may "
        "need rebinding after reinstall."
    )
    return fallback


def _workshop_paths(plugin_settings: dict[str, Any]) -> dict[str, _WorkshopResolution]:
    custom = plugin_settings.get("workshop_directory")
    roots: list[Path] = []
    if isinstance(custom, str) and custom.strip():
        candidate = Path(custom).expanduser()
        if candidate.is_absolute():
            roots.append(candidate)
    found: dict[str, _WorkshopResolution] = {}
    for item in workshop.scan(tuple(roots)):
        found[item.id] = _workshop_resolution(item)
    # A legacy custom directory usually names the content/431960 directory,
    # not a Steam library root.  Read its direct children as well.
    for root in roots:
        try:
            candidates = sorted(root.iterdir())
        except OSError:
            continue
        for candidate in candidates[: workshop.MAX_ITEMS]:
            direct = workshop._read_project(candidate)
            if direct is not None:
                found.setdefault(
                    direct.id,
                    _workshop_resolution(direct),
                )
    return found


def _workshop_resolution(item: workshop.WorkshopItem) -> _WorkshopResolution:
    if item.is_video and item.entry is not None:
        return _WorkshopResolution(item.entry, pairings.Medium.VIDEO)
    return _WorkshopResolution(item.directory, pairings.Medium.SCENE)


def _fallback_workshop_path(identifier: str) -> Path:
    roots = workshop.content_directories()
    if roots:
        return roots[0] / identifier
    return (
        Path.home()
        / ".local"
        / "share"
        / "Steam"
        / "steamapps"
        / "workshop"
        / "content"
        / workshop.APP_ID
        / identifier
    )


def _convert_pairings(
    candidates: list[dict[str, Any]],
    auto_stills: dict[str, Path],
    workshop_paths: dict[str, _WorkshopResolution],
    notes: list[str],
) -> dict[str, pairings.Pairing]:
    converted: dict[str, pairings.Pairing] = {}
    signatures: dict[str, tuple[str, str, str]] = {}
    located_auto = 0
    missing_auto = 0
    for raw in candidates:
        identity, motion, dynamic_id = _bundle_identity(raw, workshop_paths)
        still_raw = _mapping(raw.get("still"), f"legacy pairing {identity.key} still")
        still_mode = _string(still_raw.get("mode"), f"legacy pairing {identity.key} still mode")
        chosen_still: Path | None
        if still_mode == "selected":
            chosen_still = _absolute(
                still_raw.get("path"), f"legacy pairing {identity.key} selected still"
            )
            if not chosen_still.is_file():
                notes.append(
                    "One or more manually selected legacy still paths are currently missing. "
                    "Their associations were preserved without creating replacement files."
                )
        elif still_mode == "automatic" and motion is not None:
            chosen_still = auto_stills.get(dynamic_id)
            if chosen_still is None:
                missing_auto += 1
            else:
                located_auto += 1
        else:
            raise MigrationError(
                f"legacy pairing {identity.key} has invalid still mode {still_mode!r}"
            )
        policy = _palette_policy(raw.get("theme"), identity.key)
        signature = (str(chosen_still or ""), policy.encode(), policy.mode.value)
        previous = signatures.get(identity.key)
        if previous is not None and previous != signature:
            raise MigrationError(
                "legacy playlist occurrences contain different still/theme choices for the same "
                f"wallpaper {identity.key!r}; the current shared-metadata model cannot "
                "collapse them safely"
            )
        signatures[identity.key] = signature
        # Persist every recovered policy.  Legacy entries carried explicit
        # snapshots even when `customized=false`; dropping those snapshots
        # would make a later change of application defaults rewrite history.
        converted[identity.key] = pairings.Pairing(
            identity=identity,
            still=chosen_still,
            motion=motion,
            palette=policy,
            customized=True,
        )
        if len(converted) > pairings.MAX_PAIRINGS:
            raise MigrationError(
                f"legacy authoring has more than {pairings.MAX_PAIRINGS} distinct pairings"
            )
    if located_auto:
        notes.append(
            f"{located_auto} legacy automatic still association(s) were recovered "
            "from ownership sidecars; the old files remain in place and are cleaned "
            "if their media is deleted."
        )
    if missing_auto:
        notes.append(
            f"{missing_auto} automatic still association(s) had no verifiable "
            "legacy sidecar and will be regenerated when needed."
        )
    return converted


def _bundle_identity(
    raw: dict[str, Any], workshop_paths: dict[str, _WorkshopResolution]
) -> tuple[pairings.Identity, Path | None, str]:
    media = raw.get("media")
    if media is None:
        still = _mapping(raw.get("still"), "legacy static pairing still")
        path = _absolute(still.get("path"), "legacy static pairing path")
        current_kind = classify(path)
        medium = pairings.Medium.VIDEO if current_kind is Kind.VIDEO else pairings.Medium.STILL
        return (
            pairings.Identity(medium, str(path)),
            path if medium is pairings.Medium.VIDEO else None,
            f"video:{path}" if medium is pairings.Medium.VIDEO else str(path),
        )
    media_map = _mapping(media, "legacy pairing media")
    kind = _string(media_map.get("kind"), "legacy pairing media kind")
    if kind == "video":
        path = _absolute(media_map.get("source"), "legacy pairing video source")
        return pairings.Identity(pairings.Medium.VIDEO, str(path)), path, f"video:{path}"
    if kind == "workshop":
        identifier = _workshop_id(media_map.get("source"), "legacy pairing Workshop source")
        resolved = workshop_paths.get(identifier)
        if resolved is not None and resolved.medium is pairings.Medium.VIDEO:
            return (
                pairings.Identity(pairings.Medium.VIDEO, str(resolved.path)),
                resolved.path,
                identifier,
            )
        return pairings.Identity(pairings.Medium.SCENE, identifier), Path(identifier), identifier
    raise MigrationError(f"legacy pairing has unsupported media kind {kind!r}")


def _palette_policy(raw: object, identity: str) -> pairings.PalettePolicy:
    theme = _mapping(raw, f"legacy pairing {identity} theme")
    mode_value = _string(theme.get("mode"), f"legacy pairing {identity} theme mode")
    source_value = _string(theme.get("source"), f"legacy pairing {identity} theme source")
    selection = _string(
        theme.get("selection"), f"legacy pairing {identity} theme selection", optional=True
    )
    if mode_value == "inherit" or source_value == "inherit":
        if mode_value != "inherit" or source_value != "inherit":
            raise MigrationError(f"legacy pairing {identity} has a half-inherited theme")
        return pairings.PalettePolicy(pairings.KEEP, "", pairings.Mode.KEEP)
    try:
        mode = pairings.Mode(mode_value)
    except ValueError as error:
        raise MigrationError(
            f"legacy pairing {identity} has unknown theme mode {mode_value!r}"
        ) from error
    if source_value == "wallpaper":
        return pairings.PalettePolicy(pairings.ADAPTIVE, selection, mode)
    if source_value in ("builtin", "community", "custom") and selection:
        return pairings.PalettePolicy(source_value, selection, mode)
    raise MigrationError(
        f"legacy pairing {identity} has unsupported palette {source_value!r}:{selection!r}"
    )


def _legacy_automatic_stills(
    roots: tuple[Path, ...], runtime_document: dict[str, Any]
) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for root in roots:
        directory = pairing_conventions.still_directory(root)
        try:
            entries = sorted(directory.iterdir())
        except OSError:
            continue
        for sidecar in entries:
            if not sidecar.name.endswith(pairing_conventions.SIDECAR_SUFFIX):
                continue
            record = _legacy_still_sidecar(sidecar)
            if record is None:
                continue
            dynamic_id, still = record
            found.setdefault(dynamic_id, still)
    # Runtime carries the exact last-used pair and helps if a user configured
    # a capture root after the still was created elsewhere.  It grants no
    # ownership on its own: only an adjacent validated sidecar is accepted.
    candidates: list[object] = []
    registry = runtime_document.get("pair_registry")
    if isinstance(registry, dict):
        candidates.extend(registry.values())
    pairs_value = runtime_document.get("pairs")
    if isinstance(pairs_value, dict):
        candidates.extend(pairs_value.values())
    for candidate in candidates:
        if not isinstance(candidate, dict):
            continue
        still_value = candidate.get("still_path")
        if not isinstance(still_value, str) or not Path(still_value).is_absolute():
            continue
        sidecar = Path(still_value + pairing_conventions.SIDECAR_SUFFIX)
        record = _legacy_still_sidecar(sidecar)
        if record is not None:
            found.setdefault(*record)
    return found


def _legacy_still_sidecar(sidecar: Path) -> tuple[str, Path] | None:
    try:
        raw = file_io.read_regular_bytes(sidecar, pairing_conventions.MAX_SIDECAR_BYTES)
    except OSError:
        return None
    if raw is None:
        return None
    try:
        document = json.loads(raw)
    except UnicodeDecodeError, ValueError, RecursionError:
        return None
    if not isinstance(document, dict):
        return None
    path_value = document.get("path")
    dynamic_id = document.get("dynamic_id")
    if (
        document.get("schema") != 1
        or document.get("plugin") != LEGACY_PLUGIN_ID
        or document.get("kind") != "automatic-still"
        or not isinstance(path_value, str)
        or not isinstance(dynamic_id, str)
        or not dynamic_id
    ):
        return None
    still = Path(path_value)
    expected = sidecar.with_name(sidecar.name[: -len(pairing_conventions.SIDECAR_SUFFIX)])
    if still != expected or not still.is_absolute() or still.is_symlink() or not still.is_file():
        return None
    return dynamic_id, still


def _convert_schedules(
    outputs: dict[str, dict[str, Any]],
    playlist_map: dict[str, str],
    notes: list[str],
    *,
    independent: bool,
) -> tuple[schedules.Rule, ...]:
    rules: list[schedules.Rule] = []
    identifiers: set[str] = set()
    for connector, output in sorted(outputs.items()):
        raw_rules = output.get("schedules", [])
        if not isinstance(raw_rules, list):
            raise MigrationError(f"legacy output {connector!r} has no schedule list")
        for ordinal, raw_rule in enumerate(raw_rules, start=1):
            rule = _mapping(raw_rule, f"legacy output {connector!r} schedule {ordinal}")
            old_id = _string(rule.get("id"), "legacy schedule id")
            identifier = _schedule_id(old_id, connector, ordinal, identifiers)
            identifiers.add(identifier)
            old_playlist = _string(rule.get("playlist"), f"legacy schedule {old_id!r} playlist")
            if old_playlist not in playlist_map:
                raise MigrationError(
                    f"legacy schedule {old_id!r} references missing playlist {old_playlist!r}"
                )
            raw_weekdays = rule.get("weekdays")
            raw_months = rule.get("months")
            if not isinstance(raw_weekdays, list):
                raise MigrationError(f"legacy schedule {old_id!r} has no weekday list")
            if raw_months is None:
                raw_months = list(range(1, 13))
            if not isinstance(raw_months, list):
                raise MigrationError(f"legacy schedule {old_id!r} has no month list")
            weekdays = frozenset(
                _integer(value, f"legacy schedule {old_id!r} weekday", 0, 6)
                for value in raw_weekdays
            )
            months = frozenset(
                _integer(value, f"legacy schedule {old_id!r} month", 1, 12) for value in raw_months
            )
            all_day = _boolean(rule.get("all_day"), f"legacy schedule {old_id!r} all_day", False)
            start = end = None
            if not all_day:
                start = _integer(
                    rule.get("start_minute"), f"legacy schedule {old_id!r} start", 0, 1439
                )
                end = _integer(rule.get("end_minute"), f"legacy schedule {old_id!r} end", 0, 1439)
                if start == end:
                    raise MigrationError(
                        f"legacy schedule {old_id!r} has an ambiguous zero-length timed window"
                    )
            rules.append(
                schedules.Rule(
                    id=identifier,
                    playlist=playlist_map[old_playlist],
                    connector=connector if independent else "",
                    weekdays=weekdays,
                    months=months,
                    start=start,
                    end=end,
                    enabled=_boolean(
                        rule.get("enabled"), f"legacy schedule {old_id!r} enabled", True
                    ),
                )
            )
    if rules:
        notes.append(
            "Per-display schedule order and last-match-wins behavior were preserved; "
            "wrapped after-midnight tails remain owned by the start day."
        )
    return tuple(rules)


def _convert_displays(
    outputs: dict[str, dict[str, Any]], playlist_map: dict[str, str]
) -> dict[str, str]:
    converted: dict[str, str] = {}
    for connector, output in outputs.items():
        fallback = output.get("fallback_playlist", "")
        if fallback in (None, ""):
            continue
        old = _string(fallback, f"legacy output {connector!r} fallback playlist")
        if old not in playlist_map:
            raise MigrationError(
                f"legacy output {connector!r} references missing fallback playlist {old!r}"
            )
        converted[connector] = playlist_map[old]
    return converted


def _convert_settings(
    plugin: dict[str, Any],
    outputs: dict[str, dict[str, Any]],
    legacy_playlists: dict[str, dict[str, Any]],
    playlist_map: dict[str, str],
    designated: str,
    notes: list[str],
) -> config.Settings:
    defaults = config.Settings()
    roots: list[Path] = []
    for key in ("capture_directory", "video_directory"):
        value = plugin.get(key)
        if isinstance(value, str) and value.strip():
            candidate = Path(value).expanduser()
            if not candidate.is_absolute():
                raise MigrationError(f"legacy plugin setting {key} is not an absolute path")
            if candidate not in roots:
                roots.append(candidate)
    scheme_value = plugin.get("color_scheme")
    scheme = scheme_value if isinstance(scheme_value, str) else defaults.preview_scheme
    if scheme not in noctalia.ALL_SCHEMES:
        notes.append(
            f"Unknown legacy colour generator {scheme!r} fell back to {defaults.preview_scheme}."
        )
        scheme = defaults.preview_scheme
    minutes = plugin.get("cycle_interval_minutes", 15)
    if type(minutes) is not int:
        minutes = 15
    cycle_interval = max(5, min(24 * 60 * 60, minutes * 60))
    order = plugin.get("cycle_order", "sequential")

    active = ""
    chosen_playlist: dict[str, Any] | None = None
    chosen_output = outputs.get(designated)
    if chosen_output is not None:
        fallback_value = chosen_output.get("fallback_playlist")
        if isinstance(fallback_value, str) and fallback_value:
            active = playlist_map.get(fallback_value, "")
            chosen_playlist = legacy_playlists.get(fallback_value)
    if chosen_playlist is not None:
        interval_value = chosen_playlist.get("interval_seconds")
        if type(interval_value) is int:
            cycle_interval = max(5, min(24 * 60 * 60, interval_value))
        order = chosen_playlist.get("order", order)

    engines = _default_legacy_engines()
    if chosen_output is not None:
        engines = _legacy_engines(chosen_output.get("engines"), f"legacy output {designated!r}")
    video = _mapping(engines.get("video"), "legacy video engine")
    scene = _mapping(engines.get("workshop"), "legacy Workshop engine")
    scene_scaling = _legacy_renderer_choice(
        scene.get("scaling"),
        LEGACY_SCALING_MAP,
        "legacy Workshop scaling",
    )
    scene_clamp = _legacy_renderer_choice(
        scene.get("clamp"),
        LEGACY_CLAMP_MAP,
        "legacy Workshop clamp",
    )
    video_enabled = _boolean(video.get("enabled"), "legacy video enabled", True)
    scene_enabled = _boolean(scene.get("enabled"), "legacy Workshop enabled", True)
    auto_pause = _boolean(video.get("auto_pause"), "legacy video auto pause", True)
    auto_pause_mode = video.get("auto_pause_mode", "FULL")
    if auto_pause and auto_pause_mode != "FULL":
        notes.append(
            f"Legacy mpv auto-pause mode {auto_pause_mode!r} has no exact current "
            "equivalent and was mapped to Pause when hidden."
        )
    if video_enabled != scene_enabled:
        notes.append(
            "The designated display enabled only one dynamic renderer; the current "
            "global dynamics switch cannot preserve that split exactly."
        )
    if len(outputs) > 1:
        distinct_engines = {
            json.dumps(
                _legacy_engines(output.get("engines"), f"legacy output {name!r}"), sort_keys=True
            )
            for name, output in outputs.items()
        }
        if len(distinct_engines) > 1:
            notes.append(
                "Per-display engine settings differed. Current global renderer settings "
                f"were taken from designated display {designated!r}; other per-display "
                "engine variants remain only in the untouched legacy config."
            )

    _report_playlist_cadence(legacy_playlists, notes)
    unsupported = _unsupported_engine_choices(engines)
    if unsupported:
        notes.append(
            "Renderer choices with no current setting were retained only in legacy config: "
            + ", ".join(unsupported)
            + "."
        )

    return config.Settings(
        roots=tuple(roots),
        preview_scheme=scheme,
        follow_noctalia_palette=True,
        cycle_interval=cycle_interval,
        cycle_enabled=bool(plugin.get("cycle_start_on_load", False)),
        shuffle=order in ("shuffle", "random"),
        dynamics_enabled=video_enabled or scene_enabled,
        video_muted=_boolean(video.get("mute"), "legacy video mute", True),
        video_when_hidden="pause" if auto_pause else "play",
        video_interpolation=renderer.DEFAULT_INTERPOLATION,
        video_hardware_decode=_boolean(
            video.get("hardware_decode"), "legacy video hardware decode", True
        ),
        scene_fps=_integer(
            scene.get("fps", scenes.DEFAULT_FPS),
            "legacy Workshop FPS",
            scenes.MIN_FPS,
            scenes.MAX_FPS,
        ),
        scene_scaling=scene_scaling,
        scene_clamp=scene_clamp,
        display_mode=(
            config.DISPLAY_MODE_INDEPENDENT if len(outputs) > 1 else config.DISPLAY_MODE_MIRRORED
        ),
        theme_source_connector=designated if len(outputs) > 1 else "",
        active_playlist=active,
        own_scene_renderer=scene_enabled,
        scan_workshop=True,
    ).validated()


def _designated_output(outputs: dict[str, dict[str, Any]], plugin: dict[str, Any]) -> str:
    configured = plugin.get("palette_output")
    if isinstance(configured, str) and configured in outputs:
        return configured
    return sorted(outputs)[0] if outputs else ""


def _legacy_renderer_choice(value: object, choices: dict[str, str], where: str) -> str:
    if not isinstance(value, str) or value not in choices:
        accepted = ", ".join(sorted(choices))
        raise MigrationError(f"{where} must be one of {accepted}")
    return choices[value]


def _report_playlist_cadence(legacy: dict[str, dict[str, Any]], notes: list[str]) -> None:
    cadences: set[tuple[object, object]] = set()
    for value in legacy.values():
        cadences.add((value.get("order"), value.get("interval_seconds")))
    if len(cadences) > 1:
        notes.append(
            "Legacy playlists used different order/interval values. The current "
            "application has one global cadence, selected from the designated "
            "display's fallback playlist."
        )


def _legacy_engines(value: object, where: str) -> dict[str, Any]:
    if value is None:
        return _default_legacy_engines()
    engines = _mapping(value, f"{where} engines")
    defaults = _default_legacy_engines()
    video = _mapping(engines.get("video", {}), f"{where} video engine")
    scene = _mapping(engines.get("workshop", {}), f"{where} Workshop engine")
    merged_video = {**_mapping(defaults["video"], "default video engine"), **video}
    merged_scene = {**_mapping(defaults["workshop"], "default Workshop engine"), **scene}
    merged_scene["flags"] = {
        **_mapping(
            _mapping(defaults["workshop"], "default Workshop engine")["flags"], "default flags"
        ),
        **_mapping(scene.get("flags", {}), f"{where} Workshop flags"),
    }
    return {
        "layer": engines.get("layer", "bottom"),
        "video": merged_video,
        "workshop": merged_scene,
    }


def _default_legacy_engines() -> dict[str, Any]:
    return {
        "layer": "bottom",
        "video": {
            "enabled": True,
            "mute": True,
            "hardware_decode": True,
            "auto_pause": True,
            "auto_pause_mode": "FULL",
            "options": "",
        },
        "workshop": {
            "enabled": True,
            "fps": 30,
            "volume": 0,
            "silent": True,
            "scaling": "fill",
            "clamp": "border",
            "flags": {},
        },
    }


def _unsupported_engine_choices(engines: dict[str, Any]) -> tuple[str, ...]:
    unsupported: list[str] = []
    video = _mapping(engines["video"], "legacy video engine")
    scene = _mapping(engines["workshop"], "legacy Workshop engine")
    if engines.get("layer", "bottom") != "bottom":
        unsupported.append("layer")
    if video.get("options") not in (None, ""):
        unsupported.append("mpv options")
    for key, default in (("volume", 0), ("silent", True)):
        if scene.get(key, default) != default:
            unsupported.append(f"Workshop {key}")
    flags = scene.get("flags")
    if isinstance(flags, dict) and any(value is True for value in flags.values()):
        unsupported.append("Workshop flags")
    return tuple(unsupported)


def _api_key(plugin: dict[str, Any], notes: list[str]) -> str:
    raw = plugin.get("wallhaven_api_key")
    if not isinstance(raw, str) or not raw.strip():
        return ""
    try:
        return normalise_api_key(raw)
    except ProviderError as error:
        notes.append(f"The legacy Wallhaven API key was malformed and was not imported: {error}.")
        return ""


def _targets(source: _LegacySource, converted: _Converted, created_at: str) -> tuple[_Target, ...]:
    pairings_payload = {
        "version": pairings.FORMAT_VERSION,
        "pairings": [converted.pairings[key].to_json() for key in sorted(converted.pairings)],
    }
    playlists_payload = {
        "version": playlists.FORMAT_VERSION,
        "playlists": [converted.playlists[key].to_json() for key in sorted(converted.playlists)],
    }
    schedules_payload = {
        "version": schedules.FORMAT_VERSION,
        "rules": [rule.to_json() for rule in converted.schedules],
    }
    displays_payload = {"version": displays.FORMAT_VERSION, "displays": converted.displays}
    favourites_payload = {"version": favourites.FORMAT_VERSION, "paths": []}
    report = _report(source, converted, created_at)
    targets = [
        _Target(
            "settings",
            paths.settings_path(),
            converted.settings.to_toml().encode(),
            config.MAX_SETTINGS_BYTES,
        ),
        _Target(
            "pairings",
            pairings.state_path(),
            _json_bytes(pairings_payload),
            pairings.MAX_STATE_BYTES,
        ),
        _Target(
            "playlists",
            playlists.state_path(),
            _json_bytes(playlists_payload),
            playlists.MAX_STATE_BYTES,
        ),
        _Target(
            "schedules",
            schedules.state_path(),
            _json_bytes(schedules_payload),
            schedules.MAX_STATE_BYTES,
        ),
        _Target(
            "displays",
            displays.state_path(),
            _json_bytes(displays_payload),
            displays.MAX_STATE_BYTES,
        ),
        _Target(
            "favourites",
            favourites.state_path(),
            _json_bytes(favourites_payload),
            favourites.MAX_STATE_BYTES,
        ),
        _Target("report", report_path(), report.encode(), MAX_REPORT_BYTES),
    ]
    if converted.api_key:
        targets.append(
            _Target(
                "wallhaven-key", credentials.key_path(), (converted.api_key + "\n").encode(), 4096
            )
        )
    marker = {
        "version": MIGRATION_VERSION,
        "disposition": "imported",
        "legacy_source": str(source.directory),
        "legacy_schema": source.schema,
        "legacy_digest": source.digest,
        "imported_at": created_at,
        "legacy_bytes_modified": False,
        "report": str(report_path()),
        "targets": {
            target.key: {"path": str(target.path), "sha256": target.digest} for target in targets
        },
    }
    # The marker is last: its presence means every authoring target and report
    # has already been linked durably.
    targets.append(_Target("marker", marker_path(), _json_bytes(marker), MAX_JOURNAL_BYTES))
    return tuple(targets)


def _report(source: _LegacySource, converted: _Converted, created_at: str) -> str:
    notes = "\n".join(f"- {note}" for note in converted.notes)
    designated = converted.designated_output or "(none)"
    playlist_summary = (
        f"{len(converted.playlists)} (legacy records: {converted.legacy_playlist_count})"
    )
    display_summary = f"{len(converted.displays)} (legacy outputs: {converted.legacy_output_count})"
    credential_summary = "yes, into a private app-owned file" if converted.api_key else "no"
    return f"""# Wall-in-One legacy migration report

Imported at: {created_at}

- Source: `{source.directory}`
- Source lineage: `Go08er/goober-noctalia-plugins-v5`, plugin `goober/wall-in-one`
- Legacy config schema: {converted.legacy_schema}
- Named playlists imported: {playlist_summary}
- Pairing/metadata records imported: {len(converted.pairings)}
- Schedule rules imported: {len(converted.schedules)}
- Display assignments imported: {display_summary}
- Designated palette/settings display: `{designated}`
- Wallhaven credential imported: {credential_summary}
- Legacy bytes modified: no

## Compatibility decisions and losses

{notes}

## Rollback

The source `config.json`, `runtime.json`, Noctalia plugin settings, provider markers,
and legacy automatic stills were not edited. Stop the current service before
running the old plugin again. Current authoring lives in `{paths.app_config_dir()}`
and `{paths.app_state_dir()}`; back those directories up before changing them.
"""


def _prepare_directories(has_key: bool) -> None:
    try:
        paths.ensure_directory(paths.app_state_dir())
        paths.ensure_directory(paths.app_config_dir())
        if has_key:
            directory = paths.app_config_dir()
            if directory.is_symlink():
                raise MigrationError(f"credential directory {directory} is a symbolic link")
            info = directory.stat()
            if info.st_uid != os.getuid() or not stat.S_ISDIR(info.st_mode):
                raise MigrationError(
                    f"credential directory {directory} is not a private owned directory"
                )
            directory.chmod(stat.S_IMODE(info.st_mode) & 0o700)
    except OSError as error:
        raise MigrationError(f"cannot prepare current Wall-in-One directories: {error}") from error


def _stage_targets(targets: tuple[_Target, ...], *, keep_existing: bool = False) -> None:
    for target in targets:
        if len(target.contents) > target.maximum:
            raise MigrationError(f"converted {target.key} exceeds its {target.maximum}-byte limit")
        if keep_existing and _exact_regular(target.stage, target.contents, target.maximum):
            continue
        try:
            state_file.write_atomic_text(target.stage, target.contents.decode("utf-8"))
            target.stage.chmod(0o600)
        except (OSError, UnicodeDecodeError) as error:
            raise MigrationError(
                f"cannot stage migrated {target.key} at {target.stage}: {error}"
            ) from error


def _install_targets(targets: tuple[_Target, ...]) -> None:
    for target in targets:
        if _path_exists(target.path):
            if _exact_regular(target.path, target.contents, target.maximum):
                target.stage.unlink(missing_ok=True)
                continue
            raise MigrationError(
                f"migration stopped because {target.path} now exists with different "
                "bytes; it was not overwritten"
            )
        if not _exact_regular(target.stage, target.contents, target.maximum):
            raise MigrationError(f"migration stage {target.stage} is missing or changed")
        try:
            os.link(target.stage, target.path, follow_symlinks=False)
            paths.fsync_directory(target.path.parent)
            target.stage.unlink()
            paths.fsync_directory(target.path.parent)
        except FileExistsError:
            if not _exact_regular(target.path, target.contents, target.maximum):
                raise MigrationError(
                    f"migration stopped because {target.path} appeared concurrently "
                    "and was not overwritten"
                ) from None
            try:
                target.stage.unlink(missing_ok=True)
                paths.fsync_directory(target.path.parent)
            except OSError as error:
                raise MigrationError(
                    f"installed migrated {target.key}, but could not remove exact stage "
                    f"{target.stage}: {error}"
                ) from error
        except OSError as error:
            raise MigrationError(
                f"cannot install migrated {target.key} at {target.path}: {error}"
            ) from error


def _write_no_replace(target: Path, contents: bytes) -> None:
    stage = target.with_name(f".{target.name}.legacy-choice.stage")
    state_file.write_atomic_text(stage, contents.decode("utf-8"))
    try:
        os.link(stage, target, follow_symlinks=False)
        paths.fsync_directory(target.parent)
    finally:
        stage.unlink(missing_ok=True)


def _exact_regular(path: Path, expected: bytes, maximum: int) -> bool:
    try:
        actual = file_io.read_regular_bytes(path, maximum)
    except OSError:
        return False
    return actual == expected


def _path_exists(path: Path) -> bool:
    try:
        path.lstat()
    except FileNotFoundError:
        return False
    except OSError:
        return True
    return True


def _read_journal() -> dict[str, Any] | None:
    target = journal_path()
    try:
        raw = file_io.read_regular_bytes(target, MAX_JOURNAL_BYTES)
    except OSError as error:
        raise MigrationError(f"cannot safely read migration journal {target}: {error}") from error
    if raw is None:
        return None
    document = _json_object(raw, target)
    if type(document.get("version")) is not int or document["version"] != MIGRATION_VERSION:
        raise MigrationError(f"migration journal {target} has an unsupported version")
    required_fields = {"version", "legacy_source", "legacy_digest", "created_at", "targets"}
    if set(document) != required_fields:
        raise MigrationError(f"migration journal {target} is incomplete or ambiguous")
    _recorded_path(document["legacy_source"], "migration journal legacy source")
    _sha256(document["legacy_digest"], "migration journal legacy digest")
    _timestamp(document["created_at"], "migration journal timestamp")
    raw_targets = document["targets"]
    if not isinstance(raw_targets, dict):
        raise MigrationError(f"migration journal {target} has no target digest map")
    names = set(raw_targets)
    allowed = _JOURNAL_REQUIRED_TARGETS | _IMPORTED_OPTIONAL_TARGETS
    if not _JOURNAL_REQUIRED_TARGETS <= names <= allowed:
        raise MigrationError(f"migration journal {target} has an incomplete target digest map")
    for name, digest in raw_targets.items():
        if not isinstance(name, str):
            raise MigrationError(f"migration journal {target} has a non-text target name")
        _sha256(digest, f"migration journal target {name!r} digest")
    return document


def _validate_resumable_journal(
    journal: dict[str, Any], *, source: Path, noctalia_settings: Path | None
) -> _LegacySource:
    recorded_source = _recorded_path(journal["legacy_source"], "migration journal legacy source")
    if recorded_source != source:
        raise MigrationError(
            f"migration journal {journal_path()} belongs to {recorded_source}, not {source}; "
            "no current file was overwritten"
        )
    legacy = _load_source(source, noctalia_settings)
    if journal["legacy_digest"] != legacy.digest:
        raise MigrationError(
            "legacy source changed after migration staging began; no current file was "
            f"overwritten. Restore the source matching {journal_path()} before retrying"
        )
    converted = _convert(legacy)
    targets = _targets(legacy, converted, str(journal["created_at"]))
    expected = {target.key: target.digest for target in targets}
    if journal["targets"] != expected:
        raise MigrationError(
            f"migration journal {journal_path()} does not describe this build's output"
        )
    for target in targets:
        if _path_exists(target.path) and not _exact_regular(
            target.path, target.contents, target.maximum
        ):
            raise MigrationError(
                f"interrupted migration target {target.path} exists with different or unsafe "
                "bytes; it was not overwritten"
            )
    return legacy


def _validate_completed_journal(marker: dict[str, Any] | None, journal: dict[str, Any]) -> None:
    if marker is None or marker.get("disposition") != "imported":
        raise MigrationError(
            f"migration journal {journal_path()} cannot be completed without an imported marker"
        )
    manifest = marker["targets"]
    expected = {name: entry["sha256"] for name, entry in manifest.items()}
    expected["marker"] = hashlib.sha256(_json_bytes(marker)).hexdigest()
    if (
        journal["legacy_source"] != marker["legacy_source"]
        or journal["legacy_digest"] != marker["legacy_digest"]
        or journal["created_at"] != marker["imported_at"]
        or journal["targets"] != expected
    ):
        raise MigrationError(
            f"completed migration marker {marker_path()} does not match surviving journal "
            f"{journal_path()}; the journal was preserved"
        )


def _playlist_id(old: str, ordinal: int, used_ids: set[str], used_names: set[str]) -> str:
    candidate = old.strip()
    valid = bool(candidate) and len(candidate.encode("utf-8")) <= playlists.MAX_IDENTIFIER_BYTES
    valid = valid and not any(ord(character) < 32 for character in candidate)
    # Settings.active_playlist is authored in TOML and connector/CLI surfaces
    # treat whitespace as syntax.  Keep ordinary legacy ids, but remap exotic
    # ones rather than emitting an invalid or ambiguous current document.
    valid = valid and not any(character.isspace() or character in '"\\' for character in candidate)
    valid = valid and candidate.casefold() not in {
        "all-media",
        "all media",
        "quick-choice",
        "quick choice",
    }
    valid = valid and not candidate.casefold().startswith(
        playlists.DISPLAY_QUICK_CHOICE_ID_PREFIX.casefold()
    )
    valid = (
        valid and candidate.casefold() not in used_ids and candidate.casefold() not in used_names
    )
    if valid:
        return candidate
    base = f"legacy-{ordinal}-{_short_hash(old)}"
    candidate = base
    suffix = 2
    while candidate.casefold() in used_ids or candidate.casefold() in used_names:
        candidate = f"{base}-{suffix}"
        suffix += 1
    return candidate


def _unique_playlist_name(raw: str, used: set[str]) -> str:
    clean = " ".join(raw.split())
    if not clean:
        clean = "Imported playlist"
    clean = clean[: playlists.MAX_NAME_LENGTH]
    base = clean
    suffix = 2
    while clean.casefold() in used or clean.casefold() in {
        "all-media",
        "all media",
        "quick-choice",
        "quick choice",
    }:
        ending = f" ({suffix})"
        clean = base[: playlists.MAX_NAME_LENGTH - len(ending)] + ending
        suffix += 1
    return clean


def _entry_id(old: str, playlist_id: str, ordinal: int, used: set[str]) -> str:
    candidate = old.strip()
    if (
        not candidate
        or len(candidate.encode("utf-8")) > playlists.MAX_IDENTIFIER_BYTES
        or any(ord(character) < 32 for character in candidate)
        or candidate in used
    ):
        candidate = f"legacy-entry-{ordinal}-{_short_hash(playlist_id + ':' + old)}"
    suffix = 2
    base = candidate
    while candidate in used:
        candidate = f"{base}-{suffix}"
        suffix += 1
    return candidate


def _schedule_id(old: str, connector: str, ordinal: int, used: set[str]) -> str:
    candidate = old.strip()
    if not candidate or candidate in used or len(candidate.encode("utf-8")) > 256:
        candidate = f"legacy-rule-{ordinal}-{_short_hash(connector + ':' + old)}"
    suffix = 2
    base = candidate
    while candidate in used:
        candidate = f"{base}-{suffix}"
        suffix += 1
    return candidate


def _connector(value: object, where: str) -> str:
    connector = _string(value, where)
    try:
        return schedules.clean_connector(connector)
    except schedules.ScheduleError as error:
        raise MigrationError(f"{where} is invalid: {error}") from error


def _workshop_id(value: object, where: str) -> str:
    identifier = _string(value, where)
    if not identifier.isdigit() or len(identifier) > 32:
        raise MigrationError(f"{where} is not a numeric Workshop id")
    return identifier


def _short_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8", "surrogatepass")).hexdigest()[:10]


def _json_text(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _json_bytes(value: object) -> bytes:
    return _json_text(value).encode("utf-8")


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")
